"Resource/UI/HudBowCharge.res"
{
	"ChargeMeter"
	{	
		"ControlName"		"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"4"				
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"Left"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"HorizontalLineTop"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"81"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}
	"HorizontalLineBottom"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"0"
		"ypos"			"4"
		"zpos"			"3"
		"wide"			"81"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}
	"ChargeMeterLine0"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"VerticalLine"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"1"
		"tall"			"4"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"		
	}
	"ChargeMeterLine100"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"VerticalLine"
		"xpos"			"80"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"1"
		"tall"			"4"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}				
}
	
