"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"		"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"		
	}
	"ChargeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"149"
		"ypos"			"2"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"27"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"pannetje32"
		"fgcolor"		"White"
	}	
	"ChargeLabelBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabelBG1"
		"xpos"			"150"
		"ypos"			"3"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"27"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"pannetje32"
		"fgcolor"		"Black"
	}	
	"ChargeMeter"
	{	
		"ControlName"		"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"80"
		"tall"			"16"				
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"Left"
		"dulltext"		"0"
		"brighttext"		"0"
	}		
	"HealthClusterIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"-640"
		"ypos"			"-480"
		"wide"			"36"
		"tall"			"36"
		"visible"		"0"
		"visible_minmode"	"0"
		"enabled"		"0"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"		"1"	
	}
	"HorizontalLineTop"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"81"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}
	"HorizontalLineBottom"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"0"
		"ypos"			"16"
		"zpos"			"3"
		"wide"			"81"
		"tall"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}
	"ChargeMeterLine0"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"VerticalLine"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"1"
		"tall"			"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"		
	}
	"ChargeMeterLine100"
	{
		"controlName"	"ImagePanel"
		"fieldName"		"VerticalLine"
		"xpos"			"80"
		"ypos"			"1"
		"zpos"			"3"
		"wide"			"1"
		"tall"			"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"fillcolor"		"0 0 0 255"
		"visible"			"1"
		"enabled"			"1"
	}			
}
