"Resource/UI/Customizations/HUD_Customization_Frame.res"
{
	"SafeMode"
	{
		"ControlName"									"EditablePanel"
		"fieldName"										"SafeMode"
		"xpos"											"cs-0.5"
		"ypos"											"cs-0.5+10"
		"wide"											"600"
		"tall"											"430"
		"zpos"											"50"
		"visible"										"1"
		"enabled"										"1"
		"proportionaltoparent"							"1"
		"paintbackground"								"0"
		"border"										"ReplayDefaultBorder"
//==============================================================================================================================
// TITLE BAR
//==============================================================================================================================
		"Title"
		{
			"ControlName"								"CExLabel"
			"fieldName"									"Title"
			"xpos"										"1"
			"ypos"										"1"
			"zpos"										"-1"
			"wide"										"f2"
			"tall"										"24"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"use_proportional_insets"					"1"
			"labelText"									"m0reHUD Customization"
			"font"										"HudFontSmallBold"
			"textAlignment"								"west"
			"textinsetx"								"5"
			"fgcolor"									"White"
			"paintBackground"							"1"
			"paintBackgroundtype"						"2"
			"roundedcorners"							"3"
			"bgcolor_override"							"FooterBGBlack"
		}
		"CloseButton"
		{
			"ControlName"								"CExButton"
			"fieldName"									"CloseButton"
			"xpos"										"rs1-3"
			"ypos"										"3"
			"zpos"										"20"
			"wide"										"20"
			"tall"										"20"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"labelText"									"X"
			"font"										"Symbols18"
			"textAlignment"								"center"
			"Command"									"engine cl_mainmenu_safemode 0; mat_queue_mode -1"
			"actionsignallevel"							"2"
			"sound_depressed"							"UI/buttonclick.wav"
		}
//==============================================================================================================================
// SECONDARY BAR
//==============================================================================================================================
		"SubBar"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"SubBar"
			"xpos"										"0"
			"ypos"										"0"
			"zpos"										"-1"
			"wide"										"f2"
			"tall"										"16"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"paintBackground"							"1"
			"paintBackgroundtype"						"2"
			"roundedcorners"							"12"
			"bgcolor_override"							"Black"

			"pin_to_sibling"							"Title"
			"pin_corner_to_sibling"						"PIN_CENTER_TOP"
			"pin_to_sibling_corner"						"PIN_CENTER_BOTTOM"
		}
		"GitHubWiki"
		{
			"ControlName"								"URLLabel"
			"fieldname"									"GitHubWiki"
			"xpos"										"-2"
			"ypos"										"-2"
			"zpos"										"20"
			"wide"										"240"
			"tall"										"12"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"labelText"									"Screenshots and more informations"
			"font"										"ItemFontNameSmallest"
			"textAlignment"								"center"
			"urlText"									"https://github.com/Hypnootize/m0rehud/wiki"
			"FgColor_override"							"White"
			"paintbackground"							"1"
			"paintbackgroundtype"						"2"
			"bgcolor_override"							"TanDark"

			"pin_to_sibling"							"SubBar"
		}
		"ResetAllButton"
		{
			"ControlName"								"CExButton"
			"fieldName"									"ResetAllButton"
			"xpos"										"2"
			"ypos"										"0"
			"zpos"										"20"
			"wide"										"220"
			"tall"										"12"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"labelText"									"Reset Everything To Default"
			"font"										"ItemFontNameSmallest"
			"textAlignment"								"center"
			"Command"									"engine customization_reset; hudcrosshair_reset"
			"actionsignallevel"							"2"
			"sound_depressed"							"UI/buttonclick.wav"

			"pin_to_sibling"							"GitHubWiki"
			"pin_corner_to_sibling"						"PIN_TOPLEFT"
			"pin_to_sibling_corner"						"PIN_TOPRIGHT"
		}
		"ReloadGameButton"
		{
			"ControlName"								"CExButton"
			"fieldName"									"ReloadGameButton"
			"xpos"										"2"
			"ypos"										"0"
			"zpos"										"20"
			"wide"										"131"
			"tall"										"12"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"labelText"									"Restart TF2"
			"font"										"ItemFontNameSmallest"
			"textAlignment"								"center"
			"Command"									"engine gamemenucommand RestartWithNewLanguage; mat_queue_mode -1"
			"actionsignallevel"							"2"
			"sound_depressed"							"UI/buttonclick.wav"

			"defaultBgColor_override"					"190 60 60 255"
			"armedBgColor_override"						"100 30 30 255"
			"depressedBgColor_override"					"100 30 30 255"

			"defaultFgColor_override"					"White"
			"armedFgColor_override"						"White"
			"depressedFgColor_override"					"White"

			"pin_to_sibling"							"ResetAllButton"
			"pin_corner_to_sibling"						"PIN_TOPLEFT"
			"pin_to_sibling_corner"						"PIN_TOPRIGHT"
		}
//==============================================================================================================================
// MAIN SCROLLER LIST
//==============================================================================================================================
		"Customizations_Scroller"
		{
			"ControlName"								"CScrollableList"
			"fieldName"									"Customizations_Scroller"
			"xpos"										"cs-0.5"
			"ypos"										"44"
			"zpos"										"-1"
			"wide"										"f2"
			"tall"										"f68"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"paintBackground"							"0"
			"bgcolor_override"							"Gray"

			"Scrollbar"
			{
				"xpos"									"rs1+1"
				"ypos"									"0"
				"wide"									"6"
				"tall"									"f0"
				"zpos"									"1000"
				"proportionaltoparent"					"1"

				"Slider"
				{
					"PaintBackgroundType"				"0"
					"fgcolor_override"					"Gray"
				}

				"nobuttons"								"1"
			}
			"More_Customizations_Label"
			{
				"ControlName"							"CExLabel"
				"fieldName"								"More_Customizations_Label"
				"xpos"									"cs-0.5"
				"ypos"									"770"
				"zpos"									"-1"
				"wide"									"f2"
				"tall"									"16"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"use_proportional_insets"				"1"
				"labelText"								"Animation based customizations are not present in this menu yet, check out the HUD wiki to find out how to enable and use them!"
				"font"									"FontStoreOriginalPrice"
				"textAlignment"							"west"
				"textinsetx"							"5"
				"fgcolor"								"White"
				"paintBackground"						"1"
				"paintBackgroundtype"					"0"
				"bgcolor_override"						"FooterBGBlack"
			}
			"m0reWiki"
			{
				"ControlName"							"URLLabel"
				"fieldname"								"m0reWiki"
				"xpos"									"rs1-6"
				"ypos"									"770"
				"zpos"									"20"
				"wide"									"60"
				"tall"									"16"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"labelText"								"m0re wiki"
				"font"									"ItemFontNameSmallest"
				"textAlignment"							"center"
				"urlText"								"https://github.com/Hypnootize/m0rehud/wiki"
				"fgColor_override"						"White"
				"paintbackground"						"1"
				"paintbackgroundtype"					"0"
				"bgcolor_override"						"TanDark"
			}
		}
		"ApplyButton"
		{
			"ControlName"								"CExButton"
			"fieldName"									"ApplyButton"
			"xpos"										"cs-0.5"
			"ypos"										"rs1-1"
			"zpos"										"20"
			"wide"										"f2"
			"tall"										"20"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"labelText"									"Apply Changes"
			"font"										"HudFontSmallBold"
			"textAlignment"								"center"
			"Command"									"engine cl_mainmenu_safemode 0; mat_queue_mode -1; hud_reloadscheme"
			"actionsignallevel"							"2"
			"sound_depressed"							"UI/buttonclick.wav"

			"paintbackground"							"1"
			"paintborder"								"0"
			"roundedcorners"							"0"

			"defaultBgColor_override"					"TanDark"
			"armedBgColor_override"						"TFOrange"
			"depressedBgColor_override"					"TFOrange"

			"defaultFgColor_override"					"White"
			"armedFgColor_override"						"White"
			"depressedFgColor_override"					"White"
		}
	}
}