"Resource/UI/WeaponSlots.res"
{
    "Primary"
    {
        "ControlName"							"CExLabel"
        "fieldName"								"Primary"
        "font"									"surface16"
        "labelText"								"PRIMARY"
        "fgcolor"								"0 0 0 255"
		"xpos"									"c-32"
		"ypos"									"c220"
		"zpos"									"50"
		"wide"									"f0"
		"tall"									"20"
		"visible"								"1"
		"enabled"								"1"
		"alpha"									"255"
		"textAlignment"							"center"
		"porportionaltoparent"					"1"
    }
    "Melee"
    {
        "ControlName"							"CExLabel"
        "fieldName"								"Melee"
        "font"									"surface16"
        "labelText"								"MELEE"
        "fgcolor"								"0 0 0 255"
		"xpos"									"c-24"
		"ypos"									"c200"
		"zpos"									"50"
		"wide"									"f0"
		"tall"									"20"
		"visible"								"1"
		"enabled"								"1"
		"alpha"									"255"
		"textAlignment"							"center"
		"porportionaltoparent"					"1"
    }
	"PrimarySelect"
    {
        "ControlName"							"CExLabel"
        "fieldName"								"PrimarySelect"
        "font"									"surface14"
        "labelText"								"Selected.›"
        "fgcolor"								"255 255 255 255"
		"xpos"									"c-96"
		"ypos"									"c220"
		"zpos"									"50"
		"wide"									"f0"
		"tall"									"20"
		"visible"								"1"
		"enabled"								"1"
		"alpha"									"255"
		"textAlignment"							"center"
		"porportionaltoparent"					"1"
    }
	"MeleeSelect"
    {
        "ControlName"							"CExLabel"
        "fieldName"								"MeleeSelect"
        "font"									"surface14"
        "labelText"								"Selected.›"
        "fgcolor"								"255 255 255 255"
		"xpos"									"c-82"
		"ypos"									"c200"
		"zpos"									"50"
		"wide"									"f0"
		"tall"									"20"
		"visible"								"1"
		"enabled"								"1"
		"alpha"									"255"
		"textAlignment"							"center"
		"porportionaltoparent"					"1"
    }
}