"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font_minmode"			"chippyBlack24"
        "font"          "chippyBlack36"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"5"
		"wide"			"55"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%Ammo%"

	}
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font_minmode"			"chippyBlack24"
        "font"          "chippyBlack36"
		"fgcolor"		"Black"
		"xpos"			"2"
		"ypos"			"7"
		"xpos_minmode"			"1"
		"ypos_minmode"			"6"
		"zpos"			"5"
		"wide"			"55"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%Ammo%"

	}
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
        "font"          "chippyMedium21"
		"font_minmode"			"chippyMedium16"
		"fgcolor"		"White"
		"xpos_minmode"			"25"
        "xpos"          "40"
		"ypos"			"16"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%AmmoInReserve%"
	}
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
        "font"          "chippyMedium21"
		"font_minmode"			"chippyMedium16"
		"fgcolor"		"Black"
		"xpos_minmode"			"26"
        "xpos"          "41"
		"ypos"			"17"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%AmmoInReserve%"
	}
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
        "font"          "chippyBlack36"
		"font_minmode"			"chippyBlack24"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"5"
		"wide"			"79"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%Ammo%"

	}
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
        "font"          "chippyBlack36"
		"font_minmode"			"chippyBlack24"
		"fgcolor"		"Black"
		"xpos"			"2"
		"ypos"			"7"
   		"xpos_minmode"			"1"
		"ypos_minmode"			"6"
		"zpos"			"5"
		"wide"			"79"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"left"
		"labelText"		"%Ammo%"

	}
}
