"Resource/UI/ItemModelPanel.res"
{
	"itemmodelpanel"
	{
		"ControlName"		"CEmbeddedItemModelPanel"
		"fieldName"		"itemmodelpanel"
	
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"1"		
		"wide"			"100"
		"tall"			"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"useparentbg"		"1"

		"fov"			"54"
		"start_framed"		"1"

		"disable_manipulation"	"1"

		"model"
		{
			"angles_x"		"10"
			"angles_y"		"130"
			"angles_z"		"0"
		}
	}
	"DisguiseStatusBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"DisguiseStatusBG"
		"xpos"			"-640"
		"xpos_minmode"			"10"
		"ypos"			"-480"
		"ypos_minmode"			"48"
		"zpos"			"2"
		"wide"			"23"
		"wide_minmode"			"140"
		"tall"	 		"76"
		"tall_minmode"	 		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"		"../hud/tournament_panel_black"
		"teambg_2"		"../hud/tournament_panel_red"
		"teambg_2_lodef"	"../hud/tournament_panel_red"
		"teambg_3"		"../hud/tournament_panel_blu"
		"teambg_3_lodef"	"../hud/tournament_panel_blu"
		
		"src_corner_height"		"0"				// pixels inside the image
		"src_corner_width"		"0"
			
		"draw_corner_width"		"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"	
	}
	"DisguiseBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"DisguiseBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"160"
		"tall"	 		"16"
		"autoResize"		"1"
		"pinCorner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"SqTranspBlack"
		"PaintBackgroundType"	"0"
	}
	"DisguiseName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseName"
		"xpos"			"20"
		"ypos"			"1"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%disguisename%"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
	}		
	"DisguiseNameBG1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseNameBG1"
		"xpos"			"21"
		"ypos"			"2"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%disguisename%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"DisguiseNameBG2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseNameBG2"
		"xpos"			"20"
		"ypos"			"2"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%disguisename%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"DisguiseNameBG3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DisguiseNameBG3"
		"xpos"			"21"
		"ypos"			"1"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%disguisename%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"WeaponName"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WeaponName"
		"xpos"			"20"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%weaponname%"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
	}		
	"WeaponNameBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WeaponNameBG1"
		"xpos"			"21"
		"ypos"			"10"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%weaponname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"WeaponNameBG2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WeaponNameBG2"
		"xpos"			"20"
		"ypos"			"10"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%weaponname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"WeaponNameBG3"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WeaponNameBG3"
		"xpos"			"21"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%weaponname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}			
	"SpectatorGUIHealth"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		"xpos"			"0"
		"xpos_minmode"	"10"
		"ypos"			"0"
		"ypos_minmode"	"45"
		"zpos"		"20"
		"wide"			"20"
		"tall"			"8"
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"10"
		"HealthDeathWarning"	"0.49"
		"TFFont"		"HudFontSmall"
		"HealthDeathWarningColor"	"HUDDeathWarning"
		"TextColor"		"HudOffWhite"
	}	
	
}
