"Resource/UI/FreezePanelKillerHealth.res"
{
	"PlayerStatusHealthImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImage"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"4"
		"wide"			"18"
		"tall"			"18"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"	
	}		
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"22"
		"tall"			"22"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_bg"
		"scaleImage"		"1"	
	}	
	"BuildingStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"28"
		"tall"			"28"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_equip_bg"
		"scaleImage"	"1"	
	}	
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"22"
		"tall"			"22"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_over_bg"
		"scaleImage"	"1"	
	}
	"PlayerStatusHealthValue"
	{
		"ControlName"		"Label"
		"fieldName"		"PlayerStatusHealthValue"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"5"
		"wide"			"50"
		"tall"			"18"
		"visible"		"0"
		"enabled"		"0"
		"textAlignment"		"center"	
	}				
	"KillerHealthValue"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"KillerHealthValue"
		"xpos"			"0"
		"ypos"			"1"
		"zpos"			"4"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
	}				
	"KillerHealthValueBG"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"KillerHealthValueBG"
		"xpos"			"1"
		"ypos"			"2"
		"zpos"			"3"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}				
	"KillerHealthSquare"
	{
		"ControlName" "ImagePanel"
		"fieldName"   "KillerHealthSquare"
		"xpos"	      "0"
		"ypos"        "0"
		"zpos"        "2"
		"wide"        "20"
		"tall"        "10"
		"visible"     "1"
		"enabled"     "1"
		"fillcolor"   "SqGrey"
	}	
}
