"Resource/UI/HudAccountPanel.res"
{
	"CHudAccountPanel"
	{
		"delta_item_x"			"28"
		"delta_item_start_y"	"90"
		"delta_item_end_y"		"70"
		"PositiveColor"			"0 255 0 255"
		"NegativeColor"			"255 0 0 255"
		"delta_lifetime"		"1.5"
		"delta_item_font"		"HudFontMedium"
	}
	
	"AccountBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"AccountBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"84"
		"tall"			"42"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/misc_ammo_area_blue"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/misc_ammo_area_red"
		"teambg_2_lodef"	"../hud/misc_ammo_area_red_lodef"
		"teambg_3"		"../hud/misc_ammo_area_blue"
		"teambg_3_lodef"	"../hud/misc_ammo_area_blue_lodef"
	}
	
	"MetalIcon"	
	{
		"ControlName"	"CIconPanel"
		"fieldName"		"MetalIcon"
		"xpos"			"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"ypos_lodef"	"-480"
		"zpos"			"1"
		"wide"			"10"
		"wide_lodef"	"15"
		"tall"			"10"
		"tall_lodef"	"15"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"	
		"icon"			"ico_metal"
		"iconColor"		"ProgressOffWhite"
	}
	"AccountValue"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"AccountValue"
		"xpos"			"-1"
		"ypos"			"1"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"14"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"%metal%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqGreen"
	}	
	"AccountValueBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"AccountValueBG1"
		"xpos"			"0"
		"ypos"			"2"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"14"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"%metal%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}
	"AccountValueBG2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"AccountValueBG2"
		"xpos"			"-1"
		"ypos"			"2"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"14"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"%metal%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}	
	"AccountValueBG3"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"AccountValueBG3"
		"xpos"			"0"
		"ypos"			"1"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"14"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"%metal%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}		
}
