"Resource/UI/HudDemomanPipes.res"
{
	"ChargeMeter"
	{	
		"ControlName"		"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"4"				
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"Left"
		"dulltext"		"0"
		"brighttext"		"0"
	}				
	"background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"background"
		"xpos"			"-9999"
		"ypos"			"-9999"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/misc_ammo_area_blue"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/misc_ammo_area_red"
		"teambg_2_lodef"	"../hud/misc_ammo_area_red_lodef"
		"teambg_3"		"../hud/misc_ammo_area_blue"
		"teambg_3_lodef"	"../hud/misc_ammo_area_blue_lodef"
	}
	"ChargeLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabel"
		"xpos"					"-640"
		"ypos"					"-480"
		"zpos"					"2"
		"wide"					"41"
		"tall"					"15"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"0"
		"visible_minmode"		"0"
		"enabled"				"0"
		"tabPosition"			"0"
		"labelText"				"#TF_Charge"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"TFFontSmall"
	}
	"PipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"PipesPresentPanel"
		"xpos"			"-1"
		"ypos"			"18"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"16"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"-9999"
			"ypos"			"-9999"
			"wide"			"0"
			"tall"			"0"
			"visible"		"0"
			"enabled"		"0"
			"image"			"../hud/ico_stickybomb_red"
			"scaleImage"	"1"
			"teambg_2"		"../hud/ico_stickybomb_red"
			"teambg_3"		"../hud/ico_stickybomb_blue"	
		}	
		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"0"
			"ypos"			"3"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqGreen"
		}
		"NumPipesLabelBG1"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG1"
			"xpos"			"1"
			"ypos"			"4"
			"zpos"			"2"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelBG2"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG2"
			"xpos"			"0"
			"ypos"			"4"
			"zpos"			"1"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelBG3"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG3"
			"xpos"			"1"
			"ypos"			"3"
			"zpos"			"0"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"-640"
			"ypos"			"-480"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"20"
			"tall_lodef"	"28"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"0"
			"enabled"		"0"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"mini14"
			"fgcolor"		"shadow"
		}		
	}
	"NoPipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"NoPipesPresentPanel"
		"xpos"			"-1"
		"ypos"			"18"
		"zpos"			"1"
		"wide"			"80"
		"tall"			"16"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"-9999"
			"ypos"			"-9999"
			"wide"			"0"
			"tall"			"0"
			"visible"		"0"
			"enabled"		"0"
			"image"			"../hud/ico_stickybomb_red_faded"
			"scaleImage"	"1"
			"teambg_2"		"../hud/ico_stickybomb_red_faded"
			"teambg_3"		"../hud/ico_stickybomb_blue_faded"	
		}
		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"0"
			"ypos"			"3"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqGreen"
		}
		"NumPipesLabelBG1"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG1"
			"xpos"			"1"
			"ypos"			"4"
			"zpos"			"2"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelBG2"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG2"
			"xpos"			"0"
			"ypos"			"4"
			"zpos"			"1"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelBG3"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelBG3"
			"xpos"			"1"
			"ypos"			"3"
			"zpos"			"0"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"%activepipes%"
			"textAlignment"		"center"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"0"
			"tall"			"0"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"0"
			"enabled"		"0"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"mini14"
			"fgcolor"		"shadow"
		}			
	}				
}
