"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"		"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"		
	}
	"ChargeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"-1"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"10"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqCyan"
	}	
	"ChargeLabelBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabelBG1"
		"xpos"			"0"
		"ypos"			"4"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"10"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}
	"ChargeLabelBG2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabelBG2"
		"xpos"			"-1"
		"ypos"			"4"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"10"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}	
	"ChargeLabelBG3"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ChargeLabelBG3"
		"xpos"			"0"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"10"
		"autoResize"		"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"mini14"
		"fgcolor"		"SqBlack"
	}		
	"ChargeMeter"
	{	
		"ControlName"		"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"80"
		"tall"			"16"				
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"Left"
		"dulltext"		"0"
		"brighttext"		"0"
	}		
	"HealthClusterIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"-640"
		"ypos"			"-480"
		"wide"			"36"
		"tall"			"36"
		"visible"		"0"
		"visible_minmode"	"0"
		"enabled"		"0"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"		"1"	
	}		
}
