"Resource/UI/HudObjectiveTimePanel.res"
{
	"TimeBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"TimeBG"
		"xpos"			"36"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"9"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"SqTranspBlack"
	}		
	"TimePanelBG"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"TimePanelBG"
		"xpos"			"-640"
		"xpos_minmode"	"-640"
		"xpos_hidef"	"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"zpos"			"2"
		"wide"			"78"
		"wide_minmode"	"38"
		"wide_lodef"	"90"
		"tall"			"33"
		"tall_minmode"	"23"
		"tall_lodef"	"38"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_blue_bg"	
		"scaleImage"		"1"	
	}
	"TimePanelProgressBar"
	{
		"ControlName"			"CTFProgressBar"
		"fieldName"			"TimePanelProgressBar"
		"xpos"				"-640"
		"xpos_hidef"		"-640"
		"xpos_lodef"		"-640"
		"ypos"				"-480"
		"ypos_hidef"		"-480"
		"ypos_lodef"		"-480"
		"zpos"				"4"	
		"wide"				"20"
		"wide_lodef"		"25"
		"tall"				"20"
		"tall_lodef"		"25"	
		"visible"			"1"
		"visible_minmode"	"0"
		"enabled"			"1"
		"scaleImage"			"1"
		"image"				"../hud/objectives_timepanel_progressbar"
		"color_active"			"TimerProgress.Active"
		"color_inactive"		"TimerProgress.InActive"
		"color_warning"			"TimerProgress.Warning"
		"percent_warning"		"0.75"
	}
	"WaitingForPlayersLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WaitingForPlayersLabel"
		"xpos"			"-640"
		"xpos_hidef"	"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"ypos_minmode"	"-480"
		"ypos_hidef"	"-480"
		"ypos_lodef"	"-480"
		"zpos"			"5"
		"wide"			"78"
		"wide_hidef"	"300"
		"wide_lodef"	"300"
		"tall"			"19"
		"tall_hidef"	"19"
		"tall_lodef"	"22"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_WaitingForPlayers"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"ClockSubTextTiny"
		"font_hidef"	"HudFontSmall"
		"font_lodef"	"HudFontSmall"
	}			
	"WaitingForPlayersBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"WaitingForPlayersBG"
		"xpos"			"-640"	[$WIN32]
		"xpos"			"-640"	[$X360]
		"ypos"			"-480"
		"ypos_hidef"	"-480"	//off-screen
		"ypos_lodef"	"-480"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"OvertimeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"OvertimeLabel"
		"xpos"			"-640"
		"xpos_hidef"	"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"ypos_minmode"	"-480"
		"ypos_hidef"	"-480"
		"ypos_lodef"	"-480"
		"zpos"			"5"
		"wide"			"78"
		"wide_hidef"	"300"
		"wide_lodef"	"300"
		"tall"			"19"
		"tall_hidef"	"19"
		"tall_lodef"	"22"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_Overtime"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"ClockSubText"
		"font_hidef"	"HudFontSmall"
		"font_lodef"	"HudFontSmall"
	}			
	"OvertimeBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"OvertimeBG"
		"xpos"			"-640"	[$WIN32]
		"xpos"			"-640"	[$X360]
		"ypos"			"-480"
		"ypos_hidef"	"-480"	//off-screen
		"ypos_lodef"	"-480"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"SuddenDeathLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"SuddenDeathLabel"
		"xpos"			"-640"
		"xpos_hidef"	"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"ypos_minmode"	"-480"
		"ypos_hidef"	"-480"
		"ypos_lodef"	"-480"
		"zpos"			"5"
		"wide"			"78"
		"wide_hidef"	"300"
		"wide_lodef"	"300"
		"tall"			"19"
		"tall_hidef"	"19"
		"tall_lodef"	"22"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_SuddenDeath"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"ClockSubTextSuddenDeath"
		"font_hidef"	"HudFontSmall"
		"font_lodef"	"HudFontSmall"
	}			
	"SuddenDeathBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"SuddenDeathBG"
		"xpos"			"-640"	[$WIN32]
		"xpos"			"-640"	[$X360]
		"ypos"			"-480"
		"ypos_hidef"	"-480"	//off-screen
		"ypos_lodef"	"-480"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}	
	"SetupLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SetupLabel"
		"xpos"			"-640"
		"xpos_hidef"	"-640"
		"xpos_lodef"	"-640"
		"ypos"			"-480"
		"ypos_minmode"	"-480"
		"ypos_hidef"	"-480"
		"ypos_lodef"	"-480"
		"zpos"			"5"
		"wide"			"78"
		"wide_hidef"	"300"
		"wide_lodef"	"300"
		"tall"			"19"
		"tall_hidef"	"19"
		"tall_lodef"	"22"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_Setup"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"ClockSubText"
		"font_minmode"	"ClockSubTextSuddenDeath"
		"font_hidef"	"HudFontSmall"
		"font_lodef"	"HudFontSmall"
	}	
	"SetupBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"SetupBG"
		"xpos"			"-640"	[$WIN32]
		"xpos"			"-640"	[$X360]
		"ypos"			"31"
		"ypos_hidef"	"-480"	//off-screen
		"ypos_lodef"	"-480"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"0"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}	
}
