"Resource/UI/HudPlayerHealth.res"
{	
	// player health data
	"HudPlayerHealth"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HudPlayerHealth"
		"xpos"			"c-202"
		"ypos"			"r38"
		"zpos"			"2"
		"wide"			"78"
		"tall"  		"30"
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"35"
		"HealthDeathWarning"	"0.49"
		"HealthDeathWarningColor"	"HUDDeathWarning"
	}	
	"PlayerStatusHealthImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImage"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"78"
		"tall"			"30"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"		"1"	
	}		
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"78"
		"tall"			"30"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_bg"
		"scaleImage"		"1"	
	}	
	"PlayerStatusHealthBonusImage"
	{
		"Alpha" "0"
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"tall"			"78"	
		"wide"			"30"	
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_over_bg"
		"scaleImage"		"1"
	}
	"HealthValue"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthValue"
		"xpos"			"-2"
		"ypos"			"4"
		"zpos"			"8"
		"wide"			"76"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"		"Center"	
		"font"			"mini28"
		"fgcolor"		"SqCyan"
	}						
	"HealthValueBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthValueBG1"
		"xpos"			"0"
		"ypos"			"6"
		"zpos"			"7"
		"wide"			"76"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"		"Center"	
		"font"			"mini28"
		"fgcolor"		"SqBlack"
	}		
	"HealthValueBG2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthValueBG2"
		"xpos"			"-2"
		"ypos"			"6"
		"zpos"			"6"
		"wide"			"76"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"		"Center"	
		"font"			"mini28"
		"fgcolor"		"SqBlack"
	}
	"HealthValueBG3"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthValueBG3"
		"xpos"			"0"
		"ypos"			"4"
		"zpos"			"5"
		"wide"			"76"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"		"Center"	
		"font"			"mini28"
		"fgcolor"		"SqBlack"
	}	
	"HealthSquare"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthSquare"
		"xpos"			"-51"
		"ypos"			"-15"
		"zpos"			"3"
		"wide"			"180"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"		"center"	
		"font"			"SqSquare"
		"fgcolor"		"SqGrey"
	}															
	"PlayerStatusBleedImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusBleedImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"78"
		"tall"			"30"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"		"1"	
		"image"			"../vgui/bleed_drop"
		"fgcolor"		"TanDark"
	}		
	"PlayerStatusMilkImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMilkImage"
		"xpos"			"117"
		"xpos_minmode"	"102"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop"
		"fgcolor"		"TanDark"
	}
}
