"Resource/UI/HudTournament.res"
{
	"HudTournamentBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HudTournamentBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"240"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"SqTranspBlack"
	}
	"BlueBG"
	{
		"ControlName" 		"ImagePanel"
		"fieldName"   		"TestSquare1"
		"xpos"	 		"6"
		"ypos"	 		"6"
		"zpos"			"1"
		"wide"			"111"
		"tall"			"12"
		"visible"     		"1"
		"enabled"     		"1"
		"fillcolor"   		"SqBlue"
	}	
	"RedBG"
	{
		"ControlName" 	"ImagePanel"
		"fieldName" 	"TestSquare2"
		"xpos"		"123"
		"ypos"		"6"
		"zpos"		"1"
		"wide"		"111"
		"tall"		"12"
		"visible"     	"1"
		"enabled"     	"1"
		"fillcolor"   	"SqRed"
	}	
	"TournamentLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentLabel"
		"font"			"mini7"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"5"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"wrap"			"0"
		"labelText"		"%tournamentstatelabel%"
		"textAlignment"		"center"
	}

	"HudTournamentBLUEBG"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"HudTournamentBLUEBG"
		"xpos"			"5"
		"ypos"			"5"
		"zpos"			"-1"
		"wide"			"103"
		"tall"			"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../HUD/tournament_panel_blu"

		"src_corner_height"	"15"
		"src_corner_width"	"15"
		"draw_corner_width"	"0"	
		"draw_corner_height" 	"0"	
	}
	"TournamentBLUELabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentBLUELabel"
		"font"			"mini7"
		"xpos"			"8"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%bluenamelabel%"
		"textAlignment"		"west"
		"fgcolor_override"	"255 255 255 255"

	}
	"TournamentBLUEStateLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentBLUEStateLabel"
		"font"			"mini7"
		"xpos"			"34"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%bluestate%"
		"textAlignment"		"east"
		"fgcolor_override"		"255 255 255 255"
	}
	"HudTournamentREDBG"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"HudTournamentREDBG"
		"xpos"			"112"
		"ypos"			"5"
		"zpos"			"-1"
		"wide"			"103"
		"tall"			"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../HUD/tournament_panel_red"

		"src_corner_height"	"15"				// pixels inside the image
		"src_corner_width"	"15"
		"draw_corner_width"	"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"	
	}
	"TournamentREDLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentREDLabel"
		"font"			"mini7"
		"xpos"			"151"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%rednamelabel%"
		"textAlignment"		"east"
		"fgcolor_override"		"255 255 255 255"
	}	
	"TournamentREDStateLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentREDStateLabel"
		"font"			"mini7"
		"xpos"			"125"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%redstate%"
		"textAlignment"		"west"
		"fgcolor_override"		"255 255 255 255"
	}
	"TournamentConditionLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TournamentConditionLabel"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"1"
		"wide"			"220"
		"tall"			"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"wrap"			"0"
		"labelText"		"%winconditions%"
		"textAlignment"		"center"
	}

	"HudTournamentBGHelp"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"HudTournamentBGHelp"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../HUD/tournament_panel_brown"


		"src_corner_height"	"23"				// pixels inside the image
		"src_corner_width"	"23"
		
		"draw_corner_width"	"8"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"8"	
	}
	"TournamentInstructionsLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"TournamentInstructionsLabel"
		"font"			"TFFontSmall"
		"xpos"			"-640"
		"ypos"			"-480"
		"wide"			"0"
		"tall"			"0"
		"zpos"			"1"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"wrap"			"0"
		"labelText"		"#Tournament_Instructions"
		"textAlignment"		"center"
	}
}
