"Resource/UI/SpectatorGUIHealth.res"
{
	"HealthValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HealthValue"
		"xpos"			"0"
		"ypos"			"2"
		"zpos"			"4"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqCyan"
	}				
	"HealthValueBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"HealthValueBG1"
		"xpos"			"1"
		"ypos"			"3"
		"zpos"			"3"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}				
	"HealthValueBG2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HealthValueBG2"
		"xpos"			"0"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}	
	"HealthValueBG3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HealthValueBG3"
		"xpos"			"1"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"19"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"	
		"labelText"		"%health%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		

	"HealthSquareBG"
	{
		"ControlName" "ImagePanel"
		"fieldName"   "HealthSquareBG"
		"xpos"	      "0"
		"ypos"        "0"
		"zpos"        "-1"
		"wide"        "82"
		"tall"        "34"
		"visible"     "1"
		"enabled"     "1"
		"fillcolor"   "SqGrey"
	}			
	"PlayerStatusHealthImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImage"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"20"
		"wide_minmode"	"14"
		"tall"			"8"
		"tall_minmode"	"14"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"	
	}		
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"xpos"			"-640"
		"xpos_minmode"	"6"
		"ypos"			"-480"
		"ypos_minmode"	"6"
		"zpos"			"3"
		"wide"			"22"
		"wide_minmode"	"16"
		"tall"			"22"
		"tall_minmode"	"16"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_bg"
		"scaleImage"	"1"	
	}	
	"BuildingStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BuildingStatusHealthImageBG"
		"xpos"			"-640"
		"xpos_minmode"	"2"
		"ypos"			"-480"
		"ypos_minmode"	"3"
		"zpos"			"2"
		"wide"			"28"
		"wide_minmode"	"22"
		"tall"			"28"
		"tall_minmode"	"22"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_equip_bg"
		"scaleImage"	"1"	
	}	
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"-640"
		"xpos_minmode"	"8"
		"ypos"			"-480"
		"ypos_minmode"	"8"
		"zpos"			"3"
		"wide"			"22"
		"wide_minmode"	"12"
		"tall"			"22"
		"tall_minmode"	"12"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/health_over_bg"
		"scaleImage"	"1"	
	}
}
