"Resource/UI/TargetID.res"
{
	"TargetIDBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"TargetIDBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"-1"
		"wide"			"140"
		"tall"	 		"8"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"		"../hud/color_panel_brown"
		"teambg_2"		"../hud/color_panel_red"
		"teambg_2_lodef"	"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"teambg_3_lodef"	"../hud/color_panel_blu"
		
		"src_corner_height"		"0"				// pixels inside the image
		"src_corner_width"		"0"
			
		"draw_corner_width"		"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"	
	}
	"TargetIDBG2"
	{
		"ControlName" "ImagePanel"
		"fieldName"   "TargetIDBG2"
		"xpos"	      "20"
		"ypos"        "0"
		"zpos"        "1"
		"wide"        "140"
		"tall"        "9"
		"visible"     "1"
		"enabled"     "1"
		"fillcolor"   "SqTranspBlack"
	}	
	"TargetIDBG_Spec_Blue"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"TargetIDBG_Spec_Blue"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"-1"
		"wide"			"160"
		"tall"	 		"8"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_blu"
		"image_lodef"	"../hud/color_panel_blu"
		
		"src_corner_height"		"0"				// pixels inside the image
		"src_corner_width"		"0"
			
		"draw_corner_width"		"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"
	}
	"TargetIDBG_Spec_Red"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"TargetIDBG_Spec_Red"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"-1"
		"wide"			"160"
		"tall"	 		"8"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_red"
		"image_lodef"	"../hud/color_panel_red"
		
		"src_corner_height"		"0"				// pixels inside the image
		"src_corner_width"		"0"
			
		"draw_corner_width"		"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"
	}
	"TargetNameLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TargetNameLabel"
		"xpos"			"22"
		"ypos"			"2"
		"zpos"			"5"
		"wide"			"138"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%targetname%"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
	}		
	"TargetNameLabelBG1"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TargetNameLabelBG1"
		"xpos"			"23"
		"ypos"			"3"
		"zpos"			"5"
		"wide"			"138"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%targetname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"TargetNameLabelBG2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TargetNameLabelBG2"
		"xpos"			"22"
		"ypos"			"3"
		"zpos"			"5"
		"wide"			"138"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%targetname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"TargetNameLabelBG3"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TargetNameLabelBG3"
		"xpos"			"23"
		"ypos"			"2"
		"zpos"			"5"
		"wide"			"138"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%targetname%"
		"font"			"mini7"
		"fgcolor"		"SqBlack"
	}		
	"TargetDataLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TargetDataLabel"
		"xpos"			"20"
		"ypos"			"9"
		"zpos"			"5"
		"wide"			"160"
		"tall"			"5"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"left"	
		"labelText"		"%targetdata%"
		"font"			"mini7"
		"fgcolor"		"SqWhite"
	}				
	"SpectatorGUIHealth"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		"xpos"			"0"
		"xpos_minmode"	"0"
		"ypos"			"0"
		"ypos_minmode"	"0"
		"wide"			"20"
		"tall"			"8"
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"10"
		"HealthDeathWarning"	"0.49"
		"TFFont"		"mini7"
		"HealthDeathWarningColor" "HUDDeathWarning"
		"TextColor"		"mini7"
	}	
	
	"MoveableSubPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"MoveableSubPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-5"
		"wide"			"32"
		"tall"			"36"
		"visible"		"0"
		"enabled"		"0"	
		
		"MoveableIconBG"
		{
			"ControlName"	"CIconPanel"
			"fieldName"		"MoveableIconBG"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"10"
			"tall"			"36"
			"visible"		"0"
			"enabled"		"0"
			"icon"			"obj_status_alert_background_tall_nocolor"
			"iconColor"		"HudBlack"
			"scaleImage"	"1"
		}
		
		"MoveableIcon"
		{
			"ControlName"	"CIconPanel"
			"fieldName"		"MoveableIcon"
			"xpos"			"5"
			"ypos"			"7"
			"zpos"			"11"
			"wide"			"14"
			"tall"			"14"
			"visible"		"0"
			"enabled"		"0"
			"icon"			"obj_status_sentrygun_1"
			"drawcolor"		"ProgressOffWhite"
			"scaleImage"	"1"
		}
		"MoveableSymbolIcon"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MoveableSymbolIcon"
			"xpos"			"16"
			"ypos"			"-2"
			"zpos"			"12"
			"wide"			"16"
			"tall"			"8"
			"visible"		"0"
			"enabled"		"0"
			"image"			"../hud/eng_sel_item_movable"
			"drawcolor"		"ProgressOffWhite"
			"scaleImage"	"1"
		}

		"MoveableKeyLabel"
		{	
			"ControlName"		"Label"
			"fieldName"		"MoveableKeyLabel"
			"font"			"TFFontMedium"
			"font_minmode"	"DefaultVerySmall"
			"xpos"			"0"
			"ypos"			"22"
			"zpos"			"1"
			"wide"			"640"
			"tall"			"24"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"0"
			"labelText"		"%movekey%"
			"textAlignment"		"North"
			"dulltext"		"0"
			"brighttext"		"0"
		}	
	}
}
