"Resource/UI/winpanel.res"
{
	"TeamScoresPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"TeamScoresPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"240"
		"tall"			"98"
		"visible"		"1"
		
		WinBG
		{
			"ControlName" "ImagePanel"
			"fieldName"   "WinBG"
			"xpos"	      "0"
			"ypos"        "1"
			"zpos"        "0"
			"wide"        "240"
			"tall"        "97"
			"visible"     "1"
			"enabled"     "1"
			"fillcolor"   "SqTranspBlack"
		}
		TopBar
		{
			"ControlName" "ImagePanel"
			"fieldName"   "TopBar"
			"xpos"	      "1"
			"ypos"        "2"
			"zpos"        "3"
			"wide"        "238"
			"tall"        "15"
			"visible"     "1"
			"enabled"     "1"
			"fillcolor"   "SqGrey"
		}
		TopBarBG
		{
			"ControlName" "ImagePanel"
			"fieldName"   "TopBarBG"
			"xpos"	      "0"
			"ypos"        "1"
			"zpos"        "2"
			"wide"        "240"
			"tall"        "17"
			"visible"     "1"
			"enabled"     "1"
			"fillcolor"   "SqBlack"
		}
		Divider
		{
			"ControlName" "ImagePanel"
			"fieldName"   "Divider"
			"xpos"	      "119"
			"ypos"        "1"
			"zpos"        "5"
			"wide"        "2"
			"tall"        "17"
			"visible"     "1"
			"enabled"     "1"
			"fillcolor"   "SqWhite"
		}
		DividerBG
		{
			"ControlName" "ImagePanel"
			"fieldName"   "DividerBG"
			"xpos"	      "118"
			"ypos"        "0"
			"zpos"        "4"
			"wide"        "4"
			"tall"        "19"
			"visible"     "1"
			"enabled"     "1"
			"fillcolor"   "SqBlack"
		}	
		"BlueScoreBG"
		{
			"ControlName"		"ScalableImagePanel"
			"fieldName"		"BlueScoreBG"
			"xpos"			"-640"
			"ypos"			"-480"
			"wide"			"100"
			"tall"			"12"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"0"
			"image"			"../hud/color_panel_blu"
			"src_corner_height"	"15"
			"src_corner_width"	"15"
			"draw_corner_width"	"0"	
			"draw_corner_height" 	"0"	
		}
		"RedScoreBG"
		{
			"ControlName"		"ScalableImagePanel"
			"fieldName"		"RedScoreBG"
			"xpos"			"-640"
			"ypos"			"-480"
			"wide"			"100"
			"tall"			"12"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"0"
			"image"			"../hud/color_panel_red"
			"src_corner_height"	"15"
			"src_corner_width"	"15"
			"draw_corner_width"	"0"	
			"draw_corner_height" 	"0"	
		}
		"BlueTeamLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabel"
			"font"			"mini14"
			"fgcolor"		"SqWhite"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"1"
			"ypos"			"4"
			"zpos"			"9"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}	
		"BlueTeamLabelBG1"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabelBG1"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"2"
			"ypos"			"5"
			"zpos"			"8"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}	
		"BlueTeamLabelBG2"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabelBG2"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"1"
			"ypos"			"5"
			"zpos"			"7"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}										"BlueTeamLabelBG3"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamLabelBG3"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"2"
			"ypos"			"4"
			"zpos"			"6"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}					
		"BlueTeamScore"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScore"
			"font"			"mini14"
			"fgcolor"		"SqBlue"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"xpos"			"76"
			"ypos"			"4"
			"zpos"			"9"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"BlueTeamScoreBG1"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScoreBG1"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"xpos"			"77"
			"ypos"			"5"
			"zpos"			"8"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"BlueTeamScoreBG2"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScoreBG2"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"xpos"			"76"
			"ypos"			"5"
			"zpos"			"7"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"BlueTeamScoreBG3"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"BlueTeamScoreBG3"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"xpos"			"77"
			"ypos"			"4"
			"zpos"			"6"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"RedTeamLabel"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabel"
			"font"			"mini14"
			"fgcolor"		"SqWhite"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"157"
			"ypos"			"4"
			"zpos"			"9"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"RedTeamLabelBG1"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabelBG1"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"158"
			"ypos"			"5"
			"zpos"			"8"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"RedTeamLabelBG2"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabelBG2"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"157"
			"ypos"			"5"
			"zpos"			"7"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"RedTeamLabelBG3"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamLabelBG3"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"158"
			"ypos"			"4"
			"zpos"			"6"
			"wide"			"80"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}						
		"RedTeamScore"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScore"
			"font"			"mini14"
			"fgcolor"		"SqRed"
			"labelText"		"%redteamscore%"
			"textAlignment"		"west"
			"xpos"			"122"
			"ypos"			"4"
			"zpos"			"9"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}	
		"RedTeamScoreBG1"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScoreBG1"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamscore%"
			"textAlignment"		"west"
			"xpos"			"123"
			"ypos"			"5"
			"zpos"			"8"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}		
			"RedTeamScoreBG2"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScoreBG2"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamscore%"
			"textAlignment"		"west"
			"xpos"			"122"
			"ypos"			"5"
			"zpos"			"7"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"RedTeamScoreBG3"
		{
			"ControlName"		"CExLabel"
			"fieldName"		"RedTeamScoreBG3"
			"font"			"mini14"
			"fgcolor"		"SqBlack"
			"labelText"		"%redteamscore%"
			"textAlignment"		"west"
			"xpos"			"123"
			"ypos"			"4"
			"zpos"			"6"
			"wide"			"40"
			"tall"			"10"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}								
	}
	"Player1Avatar"		[$WIN32]
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player1Avatar"
		"xpos"			"2"
		"ypos"			"20"
		"zpos"			"3"
		"wide"			"24"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"SqBlack"
	}
	"Player1Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Name"
		"xpos"			"27"	
		"ypos"			"29"
		"zpos"			"3"
		"wide"			"120"	
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" 			"mini7OL"
	}
	"Player1Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Class"
		"xpos"			"149"
		"ypos"			"29"
		"zpos"			"3"
		"wide"			"60"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" 		"mini7OL"
	}
	"Player1Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player1Score"
		"xpos"			"212"
		"ypos"			"29"
		"zpos"			"3"
		"wide"			"26"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" "mini7OL"
	}
	"Player2Avatar"		[$WIN32]
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player2Avatar"
		"xpos"			"2"
		"ypos"			"46"
		"zpos"			"3"
		"wide"			"24"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"SqBlack"
	}
	"Player2Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Name"
		"xpos"			"27"	
		"ypos"			"55"
		"zpos"			"3"
		"wide"			"120"	
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" 			"mini7OL"
	}
	"Player2Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Class"
		"xpos"			"149"
		"ypos"			"55"
		"zpos"			"3"
		"wide"			"60"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" "mini7OL"
	}
	"Player2Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player2Score"
		"xpos"			"212"
		"ypos"			"55"
		"zpos"			"3"
		"wide"			"26"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" "mini7OL"
	}
	"Player3Avatar"		[$WIN32]
	{
		"ControlName"		"CAvatarImagePanel"
		"fieldName"		"Player3Avatar"
		"xpos"			"2"
		"ypos"			"72"
		"zpos"			"3"
		"wide"			"24"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"	
		"color_outline"		"SqBlack"
	}
	"Player3Name"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Name"
		"xpos"			"27"	
		"ypos"			"81"
		"zpos"			"3"
		"wide"			"120"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" 			"mini7OL"
	}
	"Player3Class"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Class"
		"xpos"			"149"
		"ypos"			"81"
		"zpos"			"3"
		"wide"			"60"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"left"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" "mini7OL"
	}
	"Player3Score"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"Player3Score"
		"xpos"			"212"
		"ypos"			"81"
		"zpos"			"3"
		"wide"			"26"
		"tall"			"5"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"font" "mini7OL"
	}
	"WinPanelBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"WinPanelBG"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"0"
		"wide"			"200"
		"tall"			"174"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"		"1"
	}
	"WinningTeamLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"WinningTeamLabel"
		"font"			"mini7OL"
		"fgcolor"   		"white"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"1"
		"wide"			"200"
		"tall"			"12"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"AdvancingTeamLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"AdvancingTeamLabel"
		"font"			"ScoreboardMedium"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"1"
		"wide"			"292"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%AdvancingTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"WinReasonLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"WinReasonLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"-480"
		"ypos"			"-640"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%WinReasonLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"DetailsLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"DetailsLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%DetailsLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"ShadedBar"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ShadedBar"
		"xpos"			"-640"
		"ypos"			"-480"
		"wide"			"200"
		"tall"			"78"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"	
		"fillcolor"		"0 0 0 153"
		"PaintBackgroundType"	"0"
	}
	"TopPlayersLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"TopPlayerLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%TopPlayersLabel%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"PointsThisRoundLabel"
	{	
		"ControlName"		"CExLabel"
		"fieldName"		"PointsThisRoundLabel"
		"font"			"ScoreboardVerySmall"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"#Winpanel_PointsThisRound"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"HorizontalLine"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HorizontalLine"
		"xpos"			"-640"
		"ypos"			"-480"
		"zpos"			"3"
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"	
		"fillcolor"		"250 234 201 255"
		"PaintBackgroundType"	"0"
	}
}
