"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"175"
		"ypos"			"170"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"				
	}
	
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"179"
		"ypos"			"123"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"TanLight"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow"
		"xpos"			"181"
		"ypos"			"125"
		"xpos_minmode"			"180"
		"ypos_minmode"			"124"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow2"
		"xpos"			"181"
		"ypos"			"123"
		"xpos_minmode"			"180"
		"ypos_minmode"			"123"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

        
	"ChargeLabelShadow3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow3"
		"xpos"			"181"
		"ypos"			"121"
		"xpos_minmode"			"180"
		"ypos_minmode"			"122"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow4"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow4"
		"xpos"			"179"
		"ypos"			"125"
		"xpos_minmode"			"179"
		"ypos_minmode"			"124"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow5"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow5"
		"xpos"			"179"
		"ypos"			"121"
		"xpos_minmode"			"179"
		"ypos_minmode"			"122"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow6"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow6"
		"xpos"			"177"
		"ypos"			"125"
		"xpos_minmode"			"178"
		"ypos_minmode"			"124"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow7"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow7"
		"xpos"			"177"
		"ypos"			"123"
		"xpos_minmode"			"178"
		"ypos_minmode"			"123"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}

	"ChargeLabelShadow8"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabelShadow8"
		"xpos"			"177"
		"ypos"			"121"
		"xpos_minmode"			"178"
		"ypos_minmode"			"122"
		"zpos"			"4"
		"wide"			"260"
		"tall"			"80"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3n"
		"font_minmode"			"HudFontGarm3nSmall"
	}
	
	"ChargeLabel2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel2"
		"xpos"			"60"
		"ypos"			"11"
		"zpos"			"3"
		"wide"			"38"
		"tall"			"14"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"center"
		"font"			"HudFontGarm3nTiny"
	}

	"ChargeLabel2Shadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel2Shadow"
		"xpos"			"61"
		"ypos"			"12"
		"zpos"			"3"
		"wide"			"38"
		"tall"			"14"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"center"
		"fgcolor"		"Garm3nHUDGreen"
		"font"			"HudFontGarm3nTiny"
	}

	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"178"
		"ypos"			"148"
		"zpos"			"2"
		"wide"			"157"
		"tall"			"28"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeterBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ChargeMeterBG"
		"xpos"		"182"
		"ypos"		"147"
		"zpos"		"1"
		"wide"		"157"
		"tall"		"35"
		"visible"	"0"
		"enabled"	"0"
		"fillcolor"	"255 170 0 255"		
	}

	"ChargeMeterBG2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ChargeMeterBG"
		"xpos"		"180"
		"ypos"		"144"
		"zpos"		"1"
		"wide"		"162"
		"tall"		"41"
		"visible"	"0"
		"enabled"	"0"
		"fillcolor"	"35 25 25 255"		
	}

        
        "IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"30"
		"xpos_minmode"			"70"
		"ypos"			"24"
		"ypos_minmode"			"110"
		"zpos"			"2"
		"wide"			"90"
		"tall"			"15"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_IndividualUberchargesMinHUD"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"HudFontSmall"
	}

        "ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"30"
		"xpos_minmode"			"40"
		"ypos"			"38"
		"ypos_minmode"			"125"
		"zpos"			"2"
		"wide"			"19"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"52"
		"xpos_minmode"			"62"
		"ypos"			"38"
		"ypos_minmode"			"125"
		"zpos"			"2"
		"wide"			"19"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"74"
		"xpos_minmode"			"84"
		"ypos"			"38"
		"ypos_minmode"			"125"
		"zpos"			"2"
		"wide"			"19"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"96"
		"xpos_minmode"			"106"
		"ypos"			"38"
		"ypos_minmode"			"125"
		"zpos"			"2"
		"wide"			"19"
		"tall"			"8"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"176"
		"ypos"			"170"
		"wide"			"50"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"	"1"	
	}

        	"ResistIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"xpos"			"0"
		"ypos"			"-2"
                "ypos_minmode"			"-2"
		"wide"			"36"
		"tall"			"36"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	
	}
	
}
