"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"9999"
		"xpos_minmode"	"2800"
		"ypos"			"9999"
		"ypos_minmode"	"7"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"9999"
		"xpos_minmode"	"2800"
		"ypos"			"9999"
		"ypos_minmode"	"7"
		"zpos"			"0"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_red_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"m0refont51"
		"fgcolor"		"255 255 255 255"
		"xpos"			"9999"
		"xpos_minmode"	"-330"
		"ypos"			"9999"
		"ypos_minmode"	"-94"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"f0"
		"tall_minmode"	"f0"
		"tall_lodef"	"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"m0refont51"
		"fgcolor"		"0 0 0 255"
		"xpos"			"9999"
		"xpos_minmode"	"-328"
		"xpos_hidef"	"2"
		"ypos"			"9999"
		"ypos_minmode"	"-92"
		"ypos_hidef"	"2"
		"ypos_lodef"	"2"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"f0"
		"tall_minmode"	"f0"
		"tall_lodef"	"f0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"	
		"labelText"		"%Ammo%"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"Default36"
		"font_lodef"	"Default36"
		"font_minmode"	"m0refont19"
		"fgcolor"		"255 255 255 255"
		"xpos"			"9999"
		"xpos_minmode"	"c97"
		"ypos"			"9999"
		"ypos_minmode"	"c128"
		"ypos_lodef"	"10"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"m0refont20"
		"font_lodef"	"HudFontMedium"
		"font_minmode"	"m0refont19"
		"fgcolor"		"0 0 0 255"
		"xpos"			"9999"
		"xpos_minmode"	"c98.75"
		"ypos"			"9999"
		"ypos_minmode"	"c129.75"
		"ypos_lodef"	"11"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"m0refont44"
		"fgcolor"		"255 255 255 255"
		"xpos"			"9999"
		"xpos_minmode"	"c31"
		"ypos"			"9999"
		"ypos_minmode"	"c112"
		"zpos"			"5"
		"wide"			"84"
		"wide_lodef"	"83"
		"tall"			"40"
		"tall_minmode"	"36"
		"tall_lodef"	"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"m0refont44"
		"fgcolor"		"0 0 0 255"
		"xpos"			"9999"
		"xpos_minmode"	"c32"
		"xpos_hidef"	"c32"
		"xpos_lodef"	"c32"
		"ypos"			"9999"
		"ypos_minmode"	"c113"
		"ypos_hidef"	"c113"
		"ypos_lodef"	"c113"
		"zpos"			"5"
		"wide"			"84"
		"wide_lodef"	"83"
		"tall"			"40"
		"tall_minmode"	"36"
		"tall_lodef"	"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-east"		
		"labelText"		"%Ammo%"
		
	}									
}
