"Resource/UI/HudAmmoWeapons.res"
{
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"Garm3nFontHuge"
		"fgcolor"		"Garm3nHUDWhite"
		"xpos"			"cs-0.5+146"
		"ypos"			"r106"
		"zpos"			"7"
		"wide"			"140"
		"tall"			"42"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"	"Garm3nFontHuge"
		"fgcolor"		"Garm3nHUDDarkGrey"
		"xpos"	"c94"
		"ypos"			"r105"
		"zpos"			"7"
		"wide"			"140"
		"tall"			"42"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%Ammo%"
	}
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"Garm3nFontBig"
		"fgcolor"		"Garm3nHUDWhite"
		"xpos"			"c135"
		"ypos"			"r105"
		"zpos"			"7"
		"wide"			"140"
		"tall"			"38"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"Garm3nFontBig"
		"fgcolor"		"0 0 0 255"
		"xpos"			"c134"
		"ypos"			"r104"
		"zpos"			"6"
		"wide"			"140"
		"tall"			"38"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
	}
}
