"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"		
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"days"
		//"fgcolor"		//"TanLight"
		fgcolor_override		"0 175 255 255"
		"xpos"			"-28"
		"ypos"			"-23"
		"zpos"			"5"
		"wide"			"100"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"days"
		"fgcolor"		"SuperBlack"
		"xpos"			"-25"
		"ypos"			"-20"
		"zpos"			"4"
		"wide"			"100"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"daysreserve"
		"fgcolor"		"TanLight"
		"xpos"			"87"
		"ypos"			"1"
		"zpos"			"7"
		"wide"			"84"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"daysreserve"
		"fgcolor"		"SuperBlack"
		"xpos"			"89"
		"ypos"			"3"
		"zpos"			"7"
		"wide"			"84"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"days"
		//"fgcolor"		//"TanLight"
		fgcolor_override		"0 175 255 255"
		"xpos"			"46"
		"ypos"			"-23"
		"zpos"			"5"
		"wide"			"170"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"days"
		"fgcolor"		"SuperBlack"
		"xpos"			"49"
		"ypos"			"-20"
		"zpos"			"5"
		"wide"			"170"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%Ammo%"
		
	}									
}
