"Resource/UI/Scoreboard.res"
{
	"scores"
	{
		"ControlName"           "CTFClientScoreBoardDialog"
		"fieldName"	 "scoreinfo"
		"xpos"          "c-300"
		"ypos"          "31"
		"wide"          "600"
		"tall"          "516"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
		"tabPosition"		"0"
		"medal_width"		"12"
		"avatar_width"		"55"
		"spacer"			"2"
		"name_width"		"85"
		"nemesis_width"		"15"
		"class_width"		"15"
		"score_width"		"20"
		"ping_width"		"20"
		"killstreak_width"	"12"
		"killstreak_image_width" "12"
		"zpos"          "20000"
     
		if_mvm
		{
			"visible"	   "0"
			"ypos"	"28"
			"xpos"          "c-300"
			"wide"          "600"
			"tall"	"438"
		}
	}
	"BlueScoreBG"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "BlueScoreBG"
		"xpos"          "45"
		"ypos"  "192"
		"wide"  "248"
		"tall"          "18"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "0"
		"enabled"	   "1"
		"bgcolor_override"       "m0reblue"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}
	"RedScoreBG"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "RedScoreBG"
		"xpos"  "305"
		"ypos"  "192"
		"wide"  "248"
		"tall"          "18"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "0"
		"enabled"	   "1"
		"bgcolor_override"       "m0rered"
		
		if_mvm
		{
			"visible"	   "0"
		}
	}
	"MainBG"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "MainBG"
		"xpos"          "46"
		"ypos"          "210"
		"zpos"	      "0"
		"wide"          "247"
		"tall"          "102"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"			           "1"
		"bgcolor_override"       "0 0 0 255"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}	  

	"MainBG2"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "MainBG2"
		"xpos"          "306"
		"ypos"          "210"
		"zpos"	      "0"
		"wide"          "247"
		"tall"          "102"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"			           "1"
		"bgcolor_override"       "0 0 0 255"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}	  
     
	"CreditsBG"
	{
		"ControlName"           "ScalableImagePanel"
		"fieldName"	 "CreditsBG"
		"xpos"          "401"
		"ypos"          "144"
		"zpos"          "0"
		"wide"          "153"
		"tall"          "148"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "0"
		"enabled"	   "1"
		"image"	     "../hud/color_panel_brown"
		"src_corner_height"     "23"			// pixels inside the image
		"src_corner_width"      "23"
		"draw_corner_width"     "3"			 // screen size of the corners ( and sides ), proportional
		"draw_corner_height"    "3"    
		"scaleImage"	"1"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}
			       
	"BlueTeamLabel"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "BlueTeamLabel"
		"font"	      "M0refont14"
		"fgcolor" "255 255 255 255"
		"labelText"	 "%blueteamname%"
		"textAlignment"         "west"
		"xpos"          "50"
		"ypos"          "192"
		"wide"          "140"
		"tall"  "18"
		"autoResize"	"0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}					      
	"BlueTeamScore"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"BlueTeamScore"
		"font"			"M0refont22"
		"fgcolor" "m0reblue"
		"labelText"		"%blueteamscore%"
		"textAlignment"		"east"
		"xpos"		"190"
		"ypos"		"179"
		"zpos"			"4"
		"wide"	"100"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		if_mvm
		{
			"visible"		"0"
		}
	}
     
	"BlueTeamPlayerCount"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "BlueTeamPlayerCount"
		"font"	      "M0refont14"
		"fgcolor" "255 255 255 255"
		"labelText"	 "%blueteamplayercount%"
		"textAlignment"         "east"
		"xpos"          "100"
		"ypos"  "192"
		"wide"  "100"
		"tall"  "18"
		"autoResize"	"0"
		"pinCorner"	 "0"
		"visible"	   "0"
		"enabled"	   "1"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}					      
	"RedTeamLabel"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "RedTeamLabel"
		"font"	      "M0refont14"
		"fgcolor" "255 255 255 255"
		"labelText"	 "%redteamname%"
		"textAlignment"         "east"
		"xpos"          "410"
		"ypos"          "192"
		"wide"          "140"
		"tall"  "18"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}					      
	"RedTeamScore"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"RedTeamScore"
		"font"			"M0refont22"
		"fgcolor" "m0reRed"
		"labelText"		"%redteamscore%"
		"textAlignment"		"west"
		"xpos"		"310"
		"ypos"		"179"
		"zpos"			"4"
		"wide"	"100"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		if_mvm
		{
			"visible"		"0"
		}
	}
     
	"RedTeamPlayerCount"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "RedTeamPlayerCount"
		"font"	      "M0refont14"
		"fgcolor" "255 255 255 255"
		"labelText"	 "%redteamplayercount%"
		"textAlignment"         "west"
		"xpos"          "400"
		"ypos"  "192"
		"wide"  "100"
		"tall"  "18"
		"autoResize"	"0"
		"pinCorner"	 "0"
		"visible"	   "0"
		"enabled"	   "1"
	       
		if_mvm
		{
			"visible"	   "0"
		}
	}
	"ServerLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"ServerLabel"
		"font"			"M0refont12"
		"fgcolor" "255 255 255 255"
		"labelText"		"%server%"
		"textAlignment"		"west"
		"xpos"		"45"
		"ypos"		"180"
		"zpos"		"-10"
		"wide"			"200"
		"tall"	"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"

		if_mvm
		{
			"visible"		"0"
		}
	}
	"ServerTimeLeft"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "ServerTimeLeft"
		"font"	      "M0refont12"
		"fgcolor" "255 255 30 255"
		"labelText"	 "%servertime%"
		"textAlignment"         "center"
		"xpos"          "c-278"
		"ypos"		"320"
		"wide"  "300"
		"tall"  "15"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
     
		if_mvm
		{
			"visible"	   "0"
		}
	}					      
	"BluePlayerList"
	{
		"ControlName"	"SectionedListPanel"
		"fieldName"		"BluePlayerList"
		"xpos"		"44"
		"ypos"		"211"
		"zpos"			"20"
		"wide"	"250"
		"tall"		"100"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"autoresize"	"3"
		"linespacing"		"15"
		"fgcolor"		"m0reBlue"
	}
	"RedPlayerList"
	{
		"ControlName"	"SectionedListPanel"
		"fieldName"		"RedPlayerList"
		"xpos"		"305"
		"ypos"		"211"
		"zpos"			"20"
		"wide"	"250"
		"tall"		"100"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"autoresize"	"3"
		"linespacing"		"15"
		"textcolor"		"m0reRed"
	}
	"VerticalLine"
	{
		"ControlName"           "ImagePanel"
		"fieldName"	 "VerticalLine"
		"xpos"          "0"
		"ypos"  "130"
		"zpos"          "2"
		"wide"          "0"
		"tall"          "0"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
		"tabPosition"   "0"    
		"fillcolor"	 "0 0 0 153"
		"PaintBackgroundType"   "0"
	}
	"Spectators"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "Spectators"
		"font"	      "M0refont8"
		"fgcolor" "255 255 255 255"
		"labelText"	 "%spectators%"
		"textAlignment"         "west"
		"xpos"          "50"
		"ypos"          "306"
		"zpos"	      "4"
		"wide"          "424"
		"tall"  "20"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
	       
		"if_mvm"
		{
			"visible"	   "0"
		}
	}      
	"SpectatorsInQueue"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "SpectatorsInQueue"
		"font"	      "M0refont8"
		"labelText"	 "%waitingtoplay%"
		"textAlignment"         "west"
		"xpos"          "50"
		"ypos"          "409"
		"zpos"	      "4"
		"wide"          "424"
		"tall"  "20"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
		"fgcolor"       "255 255 255 255"
	}					      
	"ShadedBar"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "shadedbar"
		"xpos"          "260"
		"ypos"          "325"
		"zpos"	      "0"
		"wide"          "75"
		"tall"          "30"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "0"		
		//"visible"	   "1"
		"enabled"			           "1"
		"bgcolor_override"       "0 0 0 255"
     
		if_mvm
		{
			"xpos"  "25"
			"ypos"  "415"
		}
	}
	"ClassImage"
	{
		"ControlName"           "ImagePanel"
		"fieldName"	 "ClassImage"
		"xpos"          "75"
		"ypos"          "352"
		"zpos"          "3"
		"wide"          "0"
		"tall"          "46"
		"visible"	   "1"
		"enabled"	   "1"
		"image"	     "../hud/class_scoutred"
		"scaleImage"	"1"    
	}
	"PlayerNameLabel"
	{
		"ControlName"           "CExLabel"
		"fieldName"	 "PlayerNameLabel"
		"font"	      "ScoreboardMedium"
		"labelText"	 "%playername%"
		"textAlignment"         "west"
		"xpos"          "115"
		"zpos"	      "3"
		"wide"          "0"
		"tall"          "20"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
	}					      
	"HorizontalLine"
	{
		"ControlName"   "ImagePanel"
		"fieldName"	 "HorizontalLine"
		"xpos"          "115"
		"ypos"          "397"
		"zpos"          "3"
		"wide"          "0"
		"tall"          "1"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
		"tabPosition"   "0"    
		"fillcolor"	 "127 127 127 153"
		"PaintBackgroundType"   "0"
	}
	"PlayerScoreLabel"
	{
		"ControlName"   "CExLabel"
		"fieldName"	 "PlayerScoreLabel"
		"font"          "ScoreboardMedium"
		"labelText"	 "%playerscore%"
		"textAlignment" "east"
		"xpos"          "440"
		"ypos"          "369"
		"zpos"          "3"
		"wide"          "0"
		"tall"          "0"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
	}
	"MapName"
	{
		"ControlName"   "CExLabel"
		"fieldName"	 "mapname"
		"font"	      "m0refont10"
		"labelText"	 "%mapname%"
		"textAlignment"         "center"
		"xpos"          "51"
		"ypos"          "350"
		"zpos"	      "3"
		"wide"          "101"
		"tall"          "20"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"		   "0"			
		"enabled"		   "1"
		"fgcolor"	   "255 255 255 255"
	       
		if_mvm
		{
			"ypos"	      "440"
		}
	}
     
	"LocalPlayerDuelStatsPanel"
	{
		"ControlName"           "EditablePanel"
		"fieldName"	 "LocalPlayerDuelStatsPanel"
		"xpos"          "0"
		"ypos"          "350"
		"zpos"	      "3"
		"wide"          "600"
		"tall"          "53"
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
     
		"DuelingLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"	 "DuelingLabel"
			"font"	      "M0refont12"
			"labelText"	 "#TF_ScoreBoard_Dueling"
			"textAlignment"         "center"
			"xpos"          "78"
			"ypos"          "4"
			"zpos"	      "3"
			"wide"          "0"
			"tall"          "20"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"fgcolor"	   "255 255 255 255"
		}
     
		"DuelingIcon"
		{
			"ControlName"   "ImagePanel"
			"fieldName"	 "DuelingIcon"
			"xpos"          "284"
			"ypos"          "9"
			"zpos"	      "2"
			"wide"          "32"
			"tall"          "32"
			"visible"	   "1"
			"enabled"	   "1"
			"image"	     "../backpack/player/items/crafting/icon_dueling"
			"scaleImage"    "1"
		}
     
		"LocalPlayerData"
		{
			"ControlName"           "EditablePanel"
			"fieldName"	 "LocalPlayerData"
			"xpos"          "75"
			"ypos"          "0"
			"wide"          "200"
			"tall"          "53"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
           
			"AvatarBGPanel"
			{
			        "ControlName"   "EditablePanel"
			        "fieldName"	 "AvatarBGPanel"
			        "xpos"          "157"
			        "ypos"          "7"
			        "zpos"	      "-1"
			        "wide"          "36"
			        "tall"          "36"
			        "visible"	   "1"
			        "PaintBackgroundType"   "2"
			        "bgcolor_override"      "117 107 94 255"
			}
			"AvatarImage"
			{
			        "ControlName"   "CAvatarImagePanel"
			        "fieldName"	 "AvatarImage"
			        "xpos"          "159"
			        "ypos"          "9"
			        "zpos"	      "0"
			        "wide"          "32"
			        "tall"          "32"
			        "visible"	   "1"
			        "enabled"	   "1"
			        "image"	     ""
			        "scaleImage"    "1"    
			        "color_outline" "52 48 45 255"
			}
			"AvatarTextLabel"
			{      
			        "ControlName"   "CExLabel"
			        "fieldName"	 "AvatarTextLabel"
			        "fgcolor"	   "TanLight"
			        "xpos"          "10"
			        "ypos"          "4"
			        "zpos"          "2"
			        "wide"          "140"
			        "tall"          "18"
			        "autoResize"    "0"
			        "pinCorner"	 "0"
			        "visible"	   "1"
			        "enabled"	   "1"
			        "wrap"	      "0"
			        "labelText"	 "%playername%"
			        "textAlignment" "east"
			        "font"	      "M0refont12"
			}
			"Score"
			{
			        "ControlName"   "CExLabel"
			        "fieldName"	 "Score"
			        "labelText"	 "%score%"
			        "textAlignment" "east"
			        "xpos"          "50"
			        "ypos"          "22"
			        "zpos"	      "3"
			        "wide"          "100"
			        "tall"          "25"
			        "autoResize"    "0"
			        "pinCorner"	 "0"
			        "visible"	   "1"
			        "enabled"	   "1"
			        "font"	      "M0refont22"
			        "fgcolor"	   "255 255 255 255"
			}
		}
     
		"OpponentData"
		{
			"ControlName"           "EditablePanel"
			"fieldName"	 "OpponentData"
			"xpos"          "325"
			"ypos"          "0"
			"wide"          "200"
			"tall"          "53"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
           
			"AvatarBGPanel"
			{
			        "ControlName"   "EditablePanel"
			        "fieldName"	 "AvatarBGPanel"
			        "xpos"          "7"
			        "ypos"          "7"
			        "zpos"	      "-1"
			        "wide"          "36"
			        "tall"          "36"
			        "visible"	   "1"
			        "PaintBackgroundType"   "2"
			        "bgcolor_override"      "117 107 94 255"
			}
			"AvatarImage"
			{
			        "ControlName"   "CAvatarImagePanel"
			        "fieldName"	 "AvatarImage"
			        "xpos"          "9"
			        "ypos"          "9"
			        "zpos"	      "0"
			        "wide"          ""
			        "tall"          ""
			        "visible"	   "1"
			        "enabled"	   "1"
			        "image"	     ""
			        "scaleImage"    "1"    
			        "color_outline" "52 48 45 255"
			}
			"AvatarTextLabel"
			{      
			        "ControlName"   "CExLabel"
			        "fieldName"	 "AvatarTextLabel"
			        "fgcolor"	   "TanLight"
			        "xpos"          "50"
			        "ypos"          "4"
			        "zpos"          "2"
			        "wide"          "140"
			        "tall"          "18"
			        "autoResize"    "0"
			        "pinCorner"	 "0"
			        "visible"	   "1"
			        "enabled"	   "1"
			        "wrap"	      "0"
			        "labelText"	 "%playername%"
			        "textAlignment" "west"
			        "font"	      "M0refont12"
			}
			"Score"
			{
			        "ControlName"   "CExLabel"
			        "fieldName"	 "Score"
			        "labelText"	 "%score%"
			        "textAlignment" "west"
			        "xpos"          "50"
			        "ypos"          "22"
			        "zpos"	      "3"
			        "wide"          "200"
			        "tall"          "25"
			        "autoResize"    "0"
			        "pinCorner"	 "0"
			        "visible"	   "1"
			        "enabled"	   "1"
			        "font"	      "M0refont22"
			        "fgcolor"	   "255 255 255 255"
			}
		}	  
	}
     
	"LocalPlayerStatsPanel"
	{
		"ControlName"	       "EditablePanel"
		"fieldName"			 "LocalPlayerStatsPanel"
		"xpos"			      "120"
		//"ypos"			      "319"		
		"ypos"			      "9999"
		"zpos"			      "3"
		"wide"			      "735"
		"tall"			      "50"
		"autoResize"		"0"
		"pinCorner"			 "0"
		"visible"			   "1"
		"enabled"			   "1"
	       
		if_mvm
		{
			"ypos"			"410"
		}
	       
		"KillsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "KillsLabel"
			"font"		      "M0refont8"
			"labelText"		 "#TF_ScoreBoard_KillsLabel"
			"textAlignment"         "east"
			"xpos"		      "150"
			"ypos"		      "0"
			"zpos"		      "3"
			"wide"		      "0"
			"tall"		      "0"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"enabled"		   "1"
		}
		"Kills"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Kills"
			"visible"		   "0"
		}
		"KillsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "KillsWhite"
			"font"		      "M0refont26"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%kills%"
			"textAlignment"         "east"
			"xpos"		      "126"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "50"
			"tall"		      "31"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"enabled"		   "1"
		}
	       
		"DeathsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DeathsLabel"
			"font"		      "M0refont18"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 ":"
			"textAlignment"         "west"
			"xpos"		      "172"
			"ypos"		      "6"
			"zpos"		      "3"
			"wide"		      "36"
			"tall"		      "31"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"enabled"		   "1"
		}
		"Deaths"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Deaths"
			"visible"		   "0"
		}
		"DeathsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DeathsWhite"
			"font"		      "M0refont26"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%deaths%"
			"textAlignment"         "west"
			"xpos"		      "181"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "50"
			"tall"		      "31"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"enabled"		   "1"
		}
	       
		"CapturesLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "CapturesLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_CapturesLabel"
			"textAlignment"         "east"
			"xpos"		      "175"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Captures"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Captures"
			"visible"		   "0"
		}
		"CapturesWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "CapturesWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%captures%"
			"textAlignment"         "west"
			"xpos"		      "280"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"
			"enabled"		   "1"
		}
	       
		"AssistsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "AssistsLabel"
			"fgcolor"		   "255 255 255 255"
			"font"		      "M0refont8"
			"labelText"		 "#TF_ScoreBoard_AssistsLabel"
			"textAlignment"         "east"
			"xpos"		      "175"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Assists"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Assists"
			"visible"		   "0"
		}
		"AssistsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "AssistsWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%assists%"
			"textAlignment"         "west"
			"xpos"		      "280"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"DestructionLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DestructionLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_DestructionLabel"
			"textAlignment"         "east"
			"xpos"		      "175"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Destruction"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Destruction"
			"visible"		   "0"
		}
		"DestructionWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DestructionWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%destruction%"
			"textAlignment"         "west"
			"xpos"		      "280"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"
			"enabled"		   "1"
		}
	       
		"DefensesLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DefensesLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_DefensesLabel"
			"textAlignment"         "east"
			"xpos"		      "255"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Defenses"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Defenses"
			"visible"		   "0"
		}
		"DefensesWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DefensesWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%defenses%"
			"textAlignment"         "west"
			"xpos"		      "360"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"DominationLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DominationLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_DominationLabel"
			"textAlignment"         "east"
			"xpos"		      "255"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Domination"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Domination"
			"visible"		   "0"
		}
		"DominationWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DominationWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%dominations%"
			"textAlignment"         "west"
			"xpos"		      "360"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"RevengeLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "RevengeLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_RevengeLabel"
			"textAlignment"         "east"
			"xpos"		      "255"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "100"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Revenge"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Revenge"
			"visible"		   "0"
		}
		"RevengeWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "RevengeWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%Revenge%"
			"textAlignment"         "west"
			"xpos"		      "360"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"InvulnLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "InvulnLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_InvulnLabel"
			"textAlignment"         "east"
			"xpos"		      "337"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Invuln"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Invuln"
			"visible"		   "0"
		}
		"InvulnWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "InvulnWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%invulns%"
			"textAlignment"         "west"
			"xpos"		      "437"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"HeadshotsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "HeadshotsLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_HeadshotsLabel"
			"textAlignment"         "east"
			"xpos"		      "337"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Headshots"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Headshots"
			"visible"		   "0"
		}
		"HeadshotsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "HeadshotsWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%headshots%"
			"textAlignment"         "west"
			"xpos"		      "437"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"TeleportsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "TeleportsLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_TeleportsLabel"
			"textAlignment"         "east"
			"xpos"		      "337"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Teleports"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Teleports"
			"visible"		   "0"
		}
		"TeleportsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "TeleportsWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%teleports%"
			"textAlignment"         "west"
			"xpos"		      "437"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"HealingLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "HealingLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_HealingLabel"
			"textAlignment"         "east"
			"xpos"		      "415"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Healing"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Healing"
			"visible"		   "0"
		}
		"HealingWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "HealingWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%healing%"
			"textAlignment"         "west"
			"xpos"		      "515"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"BackstabsLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "BackstabsLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_BackstabsLabel"
			"textAlignment"         "east"
			"xpos"		      "415"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"   
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Backstabs"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Backstabs"
			"visible"		   "0"
		}
		"BackstabsWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "BackstabsWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%backstabs%"
			"textAlignment"         "west"
			"xpos"		      "515"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"DamageLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DamageLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_Scoreboard_Damage"
			"textAlignment"         "east"
			"xpos"		      "415"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Damage"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Damage"
			"visible"		   "0"
		}
		"DamageWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "DamageWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%damage%"
			"textAlignment"         "west"
			"xpos"		      "515"
			"ypos"		      "35"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"BonusLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "BonusLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_ScoreBoard_BonusLabel"
			"textAlignment"         "east"
			"xpos"		      "493"
			"ypos"		      "7"
			"zpos"		      "3"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Bonus"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Bonus"
			"visible"		   "0"
		}
		"BonusWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "BonusWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%bonus%"
			"textAlignment"         "west"
			"xpos"		      "593"
			"ypos"		      "7"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	       
		"SupportLabel"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "SupportLabel"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "#TF_Scoreboard_Support"
			"textAlignment"         "east"
			"xpos"		      "493"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "95"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
		"Support"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "Support"
			"visible"		   "0"
		}
		"SupportWhite"
		{
			"ControlName"           "CExLabel"
			"fieldName"		 "SupportWhite"
			"font"		      "M0refont8"
			"fgcolor"		   "255 255 255 255"
			"labelText"		 "%support%"
			"textAlignment"         "west"
			"xpos"		      "593"
			"ypos"		      "21"
			"zpos"		      "3"
			"wide"		      "35"
			"tall"		      "20"
			"autoResize"	"0"
			"pinCorner"		 "0"
			"visible"		   "0"			
			"enabled"		   "1"
		}
	}
           
	"ButtonLegendBG"
	{
		"ControlName"   "ImagePanel"
		"fieldName"	 "ButtonLegendBG"
		"xpos"	      "10"
		"ypos"	      "373"
		"zpos"	      "0"
		"wide"	      "539"
		"tall"	      "0"	 //38
		"autoResize"    "0"
		"pinCorner"	 "0"
		"visible"	   "1"
		"enabled"	   "1"
		"tabPosition"   "0"    
		"fillcolor"	 "0 0 0 153"
		"PaintBackgroundType"   "0"
	}
           
	"ButtonLegend"
	{
		"ControlName"   "EditablePanel"
		"fieldName"	 "ButtonLegend"
		"xpos"	      "10"
		"ypos"	      "373"
		"zpos"	      "1"
		"wide"	      "539"
		"tall"	      "0"	 //150
		"visible"	   "1"
								       
		"SelectHintIcon"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "SelectHintIcon"
			"font"	      "GameUIButtons"
			"xpos"	      "10"
			"ypos"	      "0"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "38"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "C"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	       
		"SelectHintLabel"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "SelectHintLabel"
			"font"	      "ScoreboardMedium"
			"xpos"	      "25"
			"ypos"	      "2"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "39"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "#GameUI_Select"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	       
		"GamerCardIcon"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "GamerCardIcon"
			"font"	      "GameUIButtons"
			"xpos"	      "150"
			"ypos"	      "0"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "38"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "A"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	       
		"GamerCardLabel"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "GamerCardLabel"
			"font"	      "ScoreboardMedium"
			"xpos"	      "170"
			"ypos"	      "2"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "39"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "#TF_ViewGamercard"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	       
		"ReputationIcon"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "ReputationIcon"
			"font"	      "GameUIButtons"
			"xpos"	      "350"
			"ypos"	      "0"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "38"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "X"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	       
		"ReputationLabel"
		{
			"ControlName"   "CExLabel"
			"fieldName"	 "ReputationLabel"
			"font"	      "ScoreboardMedium"
			"xpos"	      "403"
			"ypos"	      "2"
			"zpos"	      "1"
			"wide"	      "300"
			"tall"	      "39"
			"autoResize"    "0"
			"pinCorner"	 "0"
			"visible"	   "1"
			"enabled"	   "1"
			"labelText"	 "#GameUI_PlayerReview"
			"textAlignment" "Left"
			"dulltext"	  "0"
			"brighttext"    "0"
		}
	}
           
	"MvMScoreboard"
	{
		"ControlName"           "CTFHudMannVsMachineScoreboard"
		"fieldName"		 "MvMScoreboard"
		"xpos"		      "0"
		"ypos"		      "0"
		"zpos"		      "10"
		"wide"		      "f0"
		"tall"		      "480"
		"visible"		   "0"
		"enabled"		   "1"
	       
		"verbose"		   "1"
	       
		if_mvm
		{
			"visible"	   "1"
		}
	}
}
