"#base"		"../basefiles/hudlayout.res"
"Resource/HudLayout.res"
{
	"HudWeaponAmmo"
	{
		"fieldName"			"HudWeaponAmmo"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c49"
		"xpos_minmode"		"c49"
		"ypos"				"r136"
		"ypos_minmode"		"r136"
		"wide"				"250"
		"tall"				"65"
	}
	"TransparentViewmodelMask"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"TransparentViewmodelMask"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-100"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"0"
		"enabled"			"0"
		"image"				"replay/thumbnails/REFRACTnormal_transparent"
		"scaleImage"		"1"
	}
	"HudKothTimeStatus"
	{
		"fieldName"		"HudKothTimeStatus"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-100"
		"ypos"			"0"
		"wide"			"200"
		"tall"			"480"
	}
	"HudItemEffectMeter"
	{
		"fieldName"			"HudItemEffectMeter"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c-37"
		"xpos_minmode"		"c-37"
		"ypos"				"r52"
		"ypos_minmode"		"r52"
		"wide"				"100"
		"tall"				"50"
		"MeterFG"			"White"
		"MeterBG"			"0 0 0 100"
		"outline"			"1"
	}
	"HudMedicCharge"
	{
		"fieldName"			"HudMedicCharge"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"0"
		"xpos_minmode"		"0"
		"ypos"				"0"
		"ypos_minmode"		"0"
		"wide"				"f0"
		"tall"				"480"
	}
	"HudDemomanCharge"
	{
		"fieldName"			"HudDemomanCharge"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c-36"
		"xpos_minmode"		"c-42"
		"ypos"				"c125"
		"ypos_minmode"		"c125"
		"zpos"				"1"
		"wide"				"82"
		"wide_minmode"		"84"
		"tall"				"3"
		"MeterFG"			"White"
		"MeterBG"			"Gray"
	}
	"HudBowCharge"
	{
		"fieldName"			"HudBowCharge"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c-42"
		"xpos_minmode"		"c-42"
		"ypos"				"c125"
		"ypos_minmode"		"c125"
		"zpos"				"1"
		"wide"				"84"
		"wide_minmode"		"84"
		"tall"				"50"
		"MeterFG"			"White"
		"MeterBG"			"Gray"
	}
	"HudFlameRocketCharge"
	{
		"fieldName"			"HudFlameRocketCharge"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c-37"
		"xpos_minmode"		"c-37"
		"ypos"				"r120"
		"ypos_minmode"		"r120"
		"zpos"				"1"
		"wide"				"100"
		"tall"				"50"
		"MeterFG"			"White"
		"MeterBG"			"Gray"
	}
	"CHudAccountPanel"
	{
		"fieldName"					"CHudAccountPanel"
		"xpos"						"c-80"
		"ypos"						"c105"
		"ypos_minmode"				"c105"
		"wide"						"160"
		"tall"						"180"
		"visible"					"1"
		"enabled"					"1"
		"PaintBackgroundType"		"2"
	}
	"CHealthAccountPanel"
	{
		"fieldName"					"CHealthAccountPanel"
		"xpos"						"0"
		"xpos_minmode"				"c-135"
		"ypos"						"460"
		"ypos_minmode"				"335"
		"wide"						"f0"
		"tall"						"24"
		"visible"					"1"
		"enabled"					"1"
		"PaintBackgroundType"		"2"
	}
	"DisguiseStatus"
	{
		"fieldName"		"DisguiseStatus"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"83"
		"ypos"			"c212"
		"wide"			"150"
		"tall"			"50"
	}
	"CMainTargetID"
	{
		"fieldName"				"CMainTargetID"
		"visible"				"0"
		"enabled"				"1"
		"xpos"					"c-126"
		"ypos"					"c30"
		"wide"					"252"
		"tall"					"24"
		"tall_minmode"			"24"
		"priority"				"40"
		"priority_lodef"		"40"
	}
	"CSpectatorTargetID"
	{
		"fieldName"				"CSpectatorTargetID"
		"visible"				"0"
		"enabled"				"1"
		"xpos"					"c-126"
		"ypos"					"c100"
		"wide"					"252"
		"tall"					"24"
		"tall_minmode"			"24"
		"priority"				"40"
		"priority_lodef"		"40"
		"x_offset"				"0"
		"y_offset"				"0"
	}
	"CSecondaryTargetID"
	{
		"fieldName"			"CSecondaryTargetID"
		"visible"			"0"
		"enabled"			"1"
		"xpos"				"c-126"
		"ypos"				"c65"
		"wide"				"252"
		"tall"				"24"
		"tall_minmode"		"24"
		"priority"			"35"
	}
	"HudRoundTimer"
	{
		"fieldName"					"HudRoundTimer"
		"xpos"						"c-50"
		"ypos"						"440"
		"wide"						"100"
		"tall"						"40"
		"visible"					"1"
		"enabled"					"1"
		"PaintBackgroundType"		"2"
		"FlashColor"				"HudIcon_Red"
		"icon_xpos"					"0"
		"icon_ypos"					"2"
		"digit_xpos"				"34"
		"digit_ypos"				"2"
	}
	"HudDamageIndicator"
	{
		"fieldName"			"HudDamageIndicator"
		"visible"			"1"
		"enabled"			"1"
		"MinimumWidth"		"11"
		"MaximumWidth"		"11"
		"StartRadius"		"80"
		"EndRadius"			"80"
		"MinimumHeight"		"30"
		"MaximumHeight"		"60"
		"MinimumTime"		"1"
	}
	"HudCrosshair"
	{
		"fieldName"		"HudCrosshair"
		"visible"		"1"
		"enabled"		"1"
		"wide"			"640"
		"tall"			"480"
	}
	"HudDeathNotice"
	{
		"fieldName"					"HudDeathNotice"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"r635"
		"ypos"						"20"
		"wide"						"628"
		"tall"						"468"
		"MaxDeathNotices"			"7"
		"IconScale"					"0.35"
		"LineHeight"				"11"
		"LineSpacing"				"1"
		"CornerRadius"				"0"
		"RightJustify"				"1"
		"TextFont"					"surface11"
		"TeamBlue"					"0 150 255 255"
		"TeamRed"					"255 0 0 255"
		"IconColor"					"255 255 255 255"
		"LocalPlayerColor"			"HUDBlack"
		"BaseBackgroundColor"		"0 0 0 0"
		"LocalBackgroundColor"		"255 255 255 200"
	}
	"HudSpellMenu"
	{
		"fieldName"				"HudSpellMenu"
		"visible"				"1"
		"enabled"				"1"
		"wide"					"640"
		"tall"					"480"
		"zpos"					"2"
		"xpos"					"c-205"
		"ypos"					"r65"
		"TextFont"				"Default"
		"ItemFont"				"Default"
		"ItemFontPulsing"		"Default"
	}
	"HudCloseCaption"
	{
		"fieldName"				"HudCloseCaption"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"c-170"
		"ypos"					"c150"
		"wide"					"150"
		"tall"					"90"
		"BgAlpha"				"0"
		"GrowTime"				"0"
		"ItemHiddenTime"		"0"
		"ItemFadeInTime"		"0"
		"ItemFadeOutTime"		"0"
		"topoffset"				"0"
	}
	"HudControlPointIcons"
	{
		"fieldName"				"HudControlPointIcons"
		"xpos"					"0"
		"ypos"					"410"
		"wide"					"f0"
		"tall"					"200"
		"visible"				"1"
		"enabled"				"1"
		"separator_width"		"2"
		"separator_height"		"5"
		"height_offset"			"0"
	}
	"WinPanel"
	{
		"fieldName"					"WinPanel"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-150"
		"ypos"						"315"
		"wide"						"300"
		"tall"						"300"
		"zpos"						"4"
		"proportionaltoparent"		"1"
	}
	"ArenaWinPanel"
	{
		"fieldName"		"ArenaWinPanel"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-145"
		"ypos"			"315"
		"wide"			"300"
		"tall"			"215"
	}
	"HudMenuEngyBuild"
	{
		"fieldName"					"HudMenuEngyBuild"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-125"
		"ypos"						"c-55"
		"wide"						"250"
		"tall"						"195"
		"PaintBackgroundType"		"0"
	}
	"HudMenuEngyDestroy"
	{
		"fieldName"					"HudMenuEngyDestroy"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-125"
		"ypos"						"c-50"
		"wide"						"250"
		"tall"						"195"
		"PaintBackgroundType"		"0"
	}
	"HudEurekaEffectTeleportMenu"
	{
		"fieldName"					"HudEurekaEffectTeleportMenu"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-125"
		"ypos"						"c-55"
		"wide"						"250"
		"tall"						"195"
		"PaintBackgroundType"		"0"
	}
	"HudMenuSpyDisguise"
	{
		"fieldName"					"HudMenuSpyDisguise"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-189"
		"ypos"						"c-92"
		"ypos_hidef"				"c-92"
		"ypos_lodef"				"c-92"
		"zpos"						"10000"
		"wide"						"378"
		"tall"						"200"
		"PaintBackgroundType"		"0"
	}
	"HudDemomanPipes"
	{
		"fieldName"		"HudDemomanPipes"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-7"
		"ypos"			"c100"
		"wide"			"284"
		"tall"			"200"
	}
	"HudArenaCapPointCountdown"
	{
		"fieldName"		"HudArenaCapPointCountdown"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-15"
		"ypos"			"447"
		"wide"			"30"
		"tall"			"30"
		"zpos"			"99"
	}
	"HudTournament"
	{
		"fieldName"			"HudTournament"
		"visible"			"0"
		"enabled"			"1"
		"xpos"				"c-225"
		"ypos"				"5"
		"ypos_lodef"		"5"
		"wide"				"450"
		"tall"				"280"
	}
	"HudChat"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"HudChat"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"0" [$WIN32]
		"xpos"						"0" [$X360]
		"ypos"						"275"
		"wide"						"320"
		"tall"						"120"
		"PaintBackgroundType"		"2"
	}
	"HudTournamentSetup"
	{
		"fieldName"			"HudTournamentSetup"
		"visible"			"0"
		"enabled"			"1"
		"xpos"				"c-90"
		"ypos"				"-70"
		"ypos_lodef"		"-70"
		"wide"				"180"
		"tall"				"65"
	}
	"HudStopWatch"
	{
		"fieldName"			"HudStopWatch"
		"visible"			"1"
		"enabled"			"1"
		"xpos"				"c-161"
		"ypos"				"-20"
		"ypos_minmode"		"-20"
		"ypos_lodef"		"-20"
		"wide"				"142"
		"tall"				"55"
	}
	"NotificationPanel"
	{
		"fieldName"		"NotificationPanel"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-320"
		"ypos"			"90"
		"zpos"			"3"
		"wide"			"640"
		"tall"			"100"
	}
	"HudAchievementTracker"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"HudAchievementTracker"
		"xpos"				"5"
		"NormalY"			"10"
		"EngineerY"			"170"
		"zpos"				"2"
		"wide"				"200"
		"tall"				"280"
		"visible"			"1"
		"enabled"			"1"
	}
	"HudInspectPanel"
	{
		"fieldName"		"HudInspectPanel"
		"visible"		"0"
		"enabled"		"1"
		"xpos"			"r230"
		"ypos"			"rs1"
		"zpos"			"10"
		"wide"			"220"
		"tall"			"f0"
	}
	"ItemQuickSwitchPanel"
	{
		"fieldName"		"ItemQuickSwitchPanel"
		"visible"		"0"
		"enabled"		"1"
		"xpos"			"0"
		"ypos"			"280"
		"wide"			"250"
		"tall"			"160"
	}
	"CoachedByPanel"
	{
		"fieldName"		"CoachedByPanel"
		"visible"		"0"
		"enable"		"1"
		"xpos"			"-4"
		"ypos"			"-6"
		"wide"			"250"
		"tall"			"44"
	}
	"HudMenuTauntSelection"
	{
		"fieldName"					"HudMenuTauntSelection"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"c-235"
		"ypos"						"c-42"
		"wide"						"470"
		"tall"						"200"
		"PaintBackgroundType"		"0"
	}
	"CDamageAccountPanel"
	{
		"xpos"		"-5"
		"ypos"		"-5"
	}
}
