"Resource/UI/HudDemomanCharge.res"
{	
	"ChargeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChargeLabel"
		"xpos"								"c210"	
		"ypos"								"423"
		"zpos"										"2"
		"wide"										"80"
		"tall"										"50"
		"autoResize"								"1"
		"pinCorner"									"2"
		"visible"									"0"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Charge:"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"		
		"font"								"M0refont10"
		"fgcolor_override"							"255 255 255 255"
	}

	"ChargeMeter"
	{	
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ChargeMeter"
		"font"										"Default"
		"xpos"								"c226"	
		"ypos"								"443"
		"zpos"										"2"
		"wide"								"40"
		"tall"								"9"			
		"autoResize"								"0"
		"pinCorner"									"0"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"Left"
		"dulltext"									"0"
		"brighttext"								"0"
		"fgcolor_override"							"255 255 255 255"
	}				
   
   "ChargeBG"
    {
		  "ControlName"     "EditablePanel"
		  "fieldName"    "ChargeMeterBG"
		  "xpos"		"c223"
		  "ypos" "440"
		  "wide"         "46"
		  "tall"   "15"    
		  "autoResize"   "0"
		  "pinCorner"    "0"
		  "visible"      "1"
		  "enabled"      "1"
		  "bgcolor_override"   "0 0 0 255"
	}				
}
