"Resource/UI/HudDemomanPipes.res"
{
	"background"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"background"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"			
	}
	
	"ChargeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChargeLabel"
		"xpos"								"c-7"
		"ypos"								"347"
		"zpos"										"2"
		"wide"										"80"
		"tall"										"50"
		"autoResize"								"1"
		"pinCorner"									"2"
		"visible"									"0"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Shield:"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"		
		"font"								"M0refont10"
		"fgcolor_override"							"255 255 255 0"
	}

	"ChargeMeter"
	{	
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ChargeMeter"	
		"xpos"								"c9"
		"ypos"								"367"
		"zpos"										"2"
		"wide"								"40"
		"tall"								"9"			
		"autoResize"								"0"
		"pinCorner"									"0"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"Left"
		"dulltext"									"0"
		"brighttext"								"0"
	}	

	"ChargeMeterBG"
	{	
		  "ControlName"     "EditablePanel"
		  "fieldName"    "ChargeMeterBG"
		  "xpos"		"c6"
		  "ypos"		"364"
		  "wide"         "46"
		  "tall"         "14"    
		  "autoResize"   "0"
		  "pinCorner"    "0"
		  "visible"      "1"
		  "enabled"      "1"
		  "bgcolor_override"   "0 0 0 255"
	}				
		
	"PipesPresentPanel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PipesPresentPanel"
		"xpos"								"-65"
		"ypos"								"68"
		"zpos"										"3"
		"wide"										"f0"
		"tall"										"480"
		"visible"									"1"
		
		"PipeIcon"
		{
			"ControlName"							"CTFImagePanel"
			"fieldName"								"PipeIcon"
			"wide"									"0"
			"tall"									"0"
			"visible"								"0"
			"enabled"								"0"
		}	
		
		"StickiesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"StickiesLabel"		
			"xpos"							"c20"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"150"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"0"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"Stickies:"
			"textAlignment"							"west"
			"dulltext"								"0"
			"brighttext"							"0"		
	    	"font"							"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}			
		
		"NumPipesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"NumPipesLabel"		
			"xpos"							"c75"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"30"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"%activepipes%"
			"textAlignment"							"center"
			"dulltext"								"0"
			"brighttext"							"0"		
		    "font"							"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}
			
		"Outof8Label"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Outof8Label"
			"xpos"									"c66"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"40"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"/8"
			"textAlignment"							"east"
			"dulltext"								"0"
			"brighttext"							"0"		
			"font"							"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}		
	}
	
	"NoPipesPresentPanel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"NoPipesPresentPanel"
		"xpos"								"-65"
		"ypos"								"68"
		"zpos"										"3"
		"wide"										"f0"
		"tall"										"480"
		"visible"									"1"
		
		"StickiesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"StickiesLabel"
			"xpos"							"c20"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"150"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"0"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"Stickies:"
			"textAlignment"							"west"
			"dulltext"								"0"
			"brighttext"							"0"		
			"font"								"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}			
		
		"NumPipesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"NumPipesLabel"	
			"xpos"							"c75"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"30"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"%activepipes%"
			"textAlignment"							"center"
			"dulltext"								"0"
			"brighttext"							"0"		
			"font"							"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}
			
		"Outof8Label"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Outof8Label"
			"xpos"									"c66"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"40"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"/8"
			"textAlignment"							"east"
			"dulltext"								"0"
			"brighttext"							"0"		
			"font"							"M0refont10"
			"fgcolor"   							"255 255 255 255"
		}
}
