"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"Omp"
		"fgcolor"		"white"
		"xpos"			"0"
		"ypos"			"-9"
		"zpos"			"5"
		"wide"			"55"
		"tall"			"50"
		"tall_lodef"	"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"Omp"
		"fgcolor"		"Black"
		"xpos"			"1"
		"xpos_hidef"	"2"
		"ypos"			"-8"
		"ypos_hidef"	"2"
		"ypos_lodef"	"2"
		"zpos"			"5"
		"wide"			"55"
		"tall"			"51"
		"tall_lodef"	"45"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"	
		"labelText"		"%Ammo%"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"FuturaHeavy14"  // "FuturaHeavy14 chippyMedium12"
		"font_lodef"	"HudFontMedium"
		"fgcolor"		"white"
		"xpos"			"42"
		"ypos"			"9"
		"ypos_lodef"	"10"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"FuturaHeavy14"
		"font_lodef"	"HudFontMedium"
		"fgcolor"		"Black"
		"xpos"			"43"
		"ypos"			"10"
		"ypos_lodef"	"11"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"27"
		"tall_lodef"	"30"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"		
		"labelText"		"%AmmoInReserve%"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"Omp"
		"fgcolor"		"white"
		"xpos"			"0"
		"ypos"			"-9"
		"zpos"			"5"
		"wide"			"79"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"Omp"
		"fgcolor"		"Black"
		"xpos"			"1"
		"ypos"			"-8"
		"zpos"			"5"
		"wide"			"79"
		"tall"			"51"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south"		
		"labelText"		"%Ammo%"
		
	}									
}
