"Resource/UI/HudItemEffectMeter_Demoman.res"
{
	HudItemEffectMeter
	{
		"fieldName"		"HudItemEffectMeter"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"-20"
		"ypos"			"r35"
		"wide"			"300"
		"tall"			"150"
		"MeterFG"		"White"
		"MeterBG"		"Gray"
	}
	
	"ItemEffectMeterBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"ItemEffectMeterBG"
		"xpos"			"12"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"76"
		"tall"			"44"
		"visible"		"0"
		
		"enabled"		"0"
		"image"			"../hud/misc_ammo_area_blue"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/misc_ammo_area_red"
		"teambg_2_lodef"	"../hud/misc_ammo_area_red_lodef"
		"teambg_3"		"../hud/misc_ammo_area_blue"
		"teambg_3_lodef"	"../hud/misc_ammo_area_blue_lodef"				
	}
	
	"ItemEffectMeterLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterLabel"
		"xpos"					"9999"
		"ypos"					"27"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_KillStreak"
		"fgcolor_override"		"Health"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
	}
	"ItemEffectMeterLabelCustom"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterLabelCustom"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"3"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"スペルカード:"
		"fgcolor_override"		"Health"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
	}
	"shdl1"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shdl1"
		"xpos"					"1"
		"ypos"					"1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"スペルカード:"
		"fgcolor_override"		"0 0 0 100"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
		"pin_to_sibling"		"ItemEffectMeterLabelCustom"
	}
	"shdl2"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shdl2"
		"xpos"					"-1"
		"ypos"					"-1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"スペルカード:"
		"fgcolor_override"		"0 0 0 100"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
		"pin_to_sibling"		"ItemEffectMeterLabelCustom"
	}
	"shdl3"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shdl3"
		"xpos"					"-1"
		"ypos"					"1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"スペルカード:"
		"fgcolor_override"		"0 0 0 100"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
		"pin_to_sibling"		"ItemEffectMeterLabelCustom"
	}
	"shdl4"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shdl4"
		"xpos"					"1"
		"ypos"					"-1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"
		"autoResize"			"1"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"スペルカード:"
		"fgcolor_override"		"0 0 0 100"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24jap"
		"pin_to_sibling"		"ItemEffectMeterLabelCustom"
	}

	"ItemEffectMeter"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ItemEffectMeter"
		"font"					"Default"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"2"
		"wide"					"40"
		"tall"					"6"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"0"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}					
	
	"ItemEffectMeterCount"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterCount"
		"xpos"					"-130"
		"ypos"					"-2"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"West"
		"fgcolor_override"		"Health"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24"
		"pin_to_sibling"		"ItemEffectMeterLabelCustom"
	}
	"shd1"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shd1"
		"xpos"					"1"
		"ypos"					"1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"West"
		"fgcolor_override"		"0 0 0 100"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24"
		"pin_to_sibling"		"ItemEffectMeterCount"
	}
	"shd2"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shd2"
		"xpos"					"-1"
		"ypos"					"-1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"West"
		"fgcolor_override"		"0 0 0 100"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24"
		"pin_to_sibling"		"ItemEffectMeterCount"
	}
	"shd3"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shd3"
		"xpos"					"1"
		"ypos"					"-1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"West"
		"fgcolor_override"		"0 0 0 100"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24"
		"pin_to_sibling"		"ItemEffectMeterCount"
	}
	"shd4"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"shd4"
		"xpos"					"-1"
		"ypos"					"1"
		"zpos"					"2"
		"wide"					"150"
		"tall"					"25"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"West"
		"fgcolor_override"		"0 0 0 100"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"toho24"
		"pin_to_sibling"		"ItemEffectMeterCount"
	}
}
