"Resource/UI/HudAmmoWeapons.res"
{
	"AmmoAnchor"
	{
		"ControlName"								"Panel"
		"fieldName"									"AmmoAnchor"
		"xpos"										"c154"
		"ypos"										"c85"
		"xpos_minmode"								"rs1-43"
		"ypos_minmode"								"rs1-13"
		"zpos"										"0"
		"wide"										"2"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
	}
	"AmmoInClip"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoInClip"
		"xpos"										"2"
		"ypos"										"1"
		"xpos_minmode"								"0"
		"ypos_minmode"								"0"
		"zpos"										"5"
		"wide"										"60"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"east"
		"labelText"									"%Ammo%"
		"font"										"HudFontMediumBig"
		"font_minmode"								"HudFontGiantBold"
		"fgcolor"									"White"

		"pin_to_sibling"							"AmmoAnchor"
		"pin_corner_to_sibling"						"PIN_TOPRIGHT"
		"pin_to_sibling_corner"						"PIN_TOPLEFT"
	}
	"AmmoInClipShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoInClipShadow"
		"xpos"										"-1"
		"ypos"										"-1"
		"xpos_minmode"								"7777"
		"ypos_minmode"								"7777"
		"zpos"										"5"
		"wide"										"60"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"east"
		"labelText"									"%Ammo%"
		"font"										"HudFontMediumBig"
		"fgcolor"									"soragray"
		"fgcolor_minmode"							"LabelTransparent"

		"pin_to_sibling"							"AmmoInClip"
	}
	"AmmoInReserve"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoInReserve"
		"xpos"										"2"
		"xpos_minmode"								"3"
		"ypos"										"7"
		"ypos_minmode"								"-7"
		"zpos"										"7"
		"wide"										"60"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"west"
		"labelText"									"%AmmoInReserve%"
		"font"										"HudFontSmallishBold"
		"font_minmode"								"HudFontSmallishBold"
		"fgcolor"									"White"

		"pin_to_sibling"							"AmmoAnchor"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_TOPRIGHT"
	}
	"AmmoInReserveShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoInReserveShadow"
		"xpos"										"-1"
		"ypos"										"0"
		"xpos_minmode"								"7777"
		"ypos_minmode"								"7777"
		"zpos"										"7"
		"wide"										"60"
		"tall"										"41"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"west"
		"labelText"									"%AmmoInReserve%"
		"font"										"HudFontSmallishBold"
		"font_minmode"								"HudFontSmallishBold"
		"fgcolor"									"soragray"
		"fgcolor_minmode"							"LabelTransparent"

		"pin_to_sibling"							"AmmoInReserve"
	}
	"AmmoNoClip"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoNoClip"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"5"
		"wide"										"80"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"center"
		"labelText"									"%Ammo%"
		"font"										"HudFontMediumBig"
		"font_minmode"								"HudFontGiantBold"
		"fgcolor"									"White"

		"pin_to_sibling"							"AmmoAnchor"
		"pin_corner_to_sibling"						"PIN_CENTER_TOP"
		"pin_to_sibling_corner"						"PIN_CENTER_TOP"
	}
	"AmmoNoClipShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"AmmoNoClipShadow"
		"xpos"										"-1"
		"ypos"										"-1"
		"xpos_minmode"								"7777"
		"ypos_minmode"								"7777"
		"zpos"										"5"
		"wide"										"80"
		"tall"										"40"
		"visible"									"0"
		"enabled"									"1"
		"textAlignment"								"center"
		"labelText"									"%Ammo%"
		"font"										"HudFontMediumBig"
		"font_minmode"								"HudFontGiantBold"
		"fgcolor"									"soragray"
		"fgcolor_minmode"							"LabelTransparent"

		"pin_to_sibling"							"AmmoNoClip"
	}

	//==================================================================================================================================================
	// REMOVED ELEMENTS
	//==================================================================================================================================================
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos_minmode"	"rs1-1"
		"ypos_minmode"	"r55"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"visible_minmode"	"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"replay/thumbnails/ammo_red_bg"
		"teambg_2_lodef"	"replay/thumbnails/ammo_red_bg_lodef"
		"teambg_3"		"replay/thumbnails/ammo_blue_bg"
		"teambg_3_lodef"	"replay/thumbnails/ammo_blue_bg_lodef"			
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"9999"
		"ypos"			"0"
		"xpos_minmode"	"9999"
		"ypos_minmode"	"rs1-15"
		"zpos"			"0"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"1"
		"image"			"replay/thumbnails/ammo_red_bg"
		"scaleImage"	"1"	
		"teambg_2"		"replay/thumbnails/ammo_red_bg"
		"teambg_2_lodef"	"replay/thumbnails/ammo_red_bg_lodef"
		"teambg_3"		"replay/thumbnails/ammo_blue_bg"
		"teambg_3_lodef"	"replay/thumbnails/ammo_blue_bg_lodef"			
	}
}