

"Resource/UI/HudAmmoWeapons.res" 
{
	"HudWeaponAmmoBG" 
	{
		"ControlName" "CTFImagePanel"
		"fieldName" "HudWeaponAmmoBG"
		"xpos" "9999"
		"ypos" "9999"
		"zpos" "1"
		"wide" "90"
		"tall" "45"
		"visible" "0"
		"enabled" "1"
		"image" "../hud/ammo_blue_bg"
		"scaleImage" "1"
		"teambg_2" "../hud/ammo_red_bg"
		"teambg_2_lodef" "../hud/ammo_red_bg_lodef"
		"teambg_3" "../hud/ammo_blue_bg"
		"teambg_3_lodef" "../hud/ammo_blue_bg_lodef"
	}
		"HudWeaponLowAmmoImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "HudWeaponLowAmmoImage"
		"xpos" "9999"
		"ypos" "9999"
		"zpos" "0"
		"wide" "90"
		"tall" "45"
		"visible" "0"
		"enabled" "0"
		"image" "../hud/ammo_red_bg"
		"scaleImage" "1"
		"teambg_2" "../hud/ammo_red_bg"
		"teambg_2_lodef" "../hud/ammo_red_bg_lodef"
		"teambg_3" "../hud/ammo_blue_bg"
		"teambg_3_lodef" "../hud/ammo_blue_bg_lodef"
	}
		"AmmoInClip" 
	{
		"ControlName" "CExLabel"
		"fieldName" "AmmoInClip"
		"font" "HandelGothicBT30"
		"fgcolor" "255 255 255 255"
		"xpos" "410"
		"ypos" "318"
		"zpos" "5"
		"wide" "80"
		"tall" "80"
		"visible" "1"
		"enabled" "1"
		"textAlignment" "north-east"
		"labelText" "%Ammo%"
	}
		"AmmoInClipShadow" 
	{
		"ControlName" "CExLabel"
		"fieldName" "AmmoInClipShadow"
		"font" "HandelGothicBT30"
		"fgcolor" "34 34 34 255"
		"xpos" "411"
		"ypos" "319"
		"zpos" "5"
		"wide" "80"
		"tall" "80"
		"visible" "0"
		"enabled" "1"
		"textAlignment" "north-east"
		"labelText" "%Ammo%"
	}
		"AmmoInReserve" 
	{
		"ControlName" "CExLabel"
		"fieldName" "AmmoInReserve"
		"font" "HandelGothicBT15"
		"fgcolor" "255 255 255 255"
		"xpos" "508"
		"ypos" "328"
		"zpos" "7"
		"wide" "90"
		"tall" "80"
		"visible" "1"
		"enabled" "1"
		"textAlignment" "north-west"
		"labelText" "%AmmoInReserve%"
	}
		"AmmoInReserveShadow" 
		{
		"ControlName" "CExLabel"
		"fieldName" "AmmoInReserveShadow"
		"font" "HandelGothicBT15"
		"fgcolor" "34 34 34 255"
		"xpos" "509"
		"ypos" "329"
		"zpos" "7"
		"wide" "90"
		"tall" "80"
		"visible" "0"
		"enabled" "1"
		"textAlignment" "north-west"
		"labelText" "%AmmoInReserve%"
		}
		"AmmoNoClip" 
	{
		"ControlName" "CExLabel"
		"fieldName" "AmmoNoClip"
		"font" "HandelGothicBT30"
		"fgcolor" "255 255 255 255"
		"xpos" "450"
		"ypos" "318"
		"zpos" "5"
		"wide" "100"
		"tall" "80"
		"visible" "0"
		"enabled" "1"
		"textAlignment" "north"
		"labelText" "%Ammo%"
	}
		"AmmoNoClipShadow" 
	{
		"ControlName" "CExLabel"
		"fieldName" "AmmoNoClipShadow"
		"font" "HandelGothicBT30"
		"fgcolor" "34 34 34 255"
		"xpos" "451"
		"ypos" "319"
		"zpos" "5"
		"wide" "100"
		"tall" "80"
		"visible" "0"
		"enabled" "1"
		"textAlignment" "north"
		"labelText" "%Ammo%"
	}
}
