

"Resource/UI/HudMedicCharge.res" 
{
"ChargeLabel" 
{
"ControlName" "CExLabel"
"fieldName" "ChargeLabel"
"xpos" "480"
"ypos" "302"
"zpos" "2"
"wide" "120"
"tall" "50"
"autoResize" "1"
"pinCorner" "2"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" "#TF_UberchargeMinHUD"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"font" "HandelGothicBT30DropShadow" 
"fgcolor" "TanLight"
}

"ChargeMeter" 
{
"ControlName" "ContinuousProgressBar"
"fieldName" "ChargeMeter"
"font" "m0refont10"
"xpos" "370"
"ypos" "430"
"zpos" "1"
"wide" "120"
"tall" "10"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"textAlignment" "north-west"
"bgcolor_override" "TanDarker"
"fgcolor_override" "TanLight"
"dulltext" "0"
"brighttext" "0"
}
"ResistIconAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"ResistIconAnchor"
		"xpos"										"423"
		"ypos"										"c150"
		"wide"										"30"
		"tall"										"30"
		"visible"									"1"
		"enabled"									"1"
	}
	
	"ResistIcon"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"ResistIcon"
		"xpos"										"0"
		"ypos"										"0"
		"wide"										"28"
		"wide_minmode"								"22"
		"tall"										"28"
		"tall_minmode"								"22"
		"visible"									"1"
		"enabled"									"1"
		"image"										"../HUD/defense_buff_bullet_blue"
		"scaleImage"								"1"
		"pin_to_sibling"							"ResistIconAnchor"
		"pin_corner_to_sibling"						"1"
		"pin_to_sibling_corner"						"1"
	}

	"IndividualChargesLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"IndividualChargesLabel"
		"xpos" "350"
		"ypos" "445"
		"zpos"					"2"
		"wide"					"190"
		"tall"					"25"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_IndividualUbercharges"
		"textAlignment"			"east"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"HandelGothicBT24"
		"fgcolor_override"				"HUDWhite"
	}

	"ChargeMeter1"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter1"
		"font"					"Default"
		"xpos" 					"360"
		"ypos" 					"430"
		"zpos"					"2"
		"wide"					"25"
		"tall"					"8"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}

	"ChargeMeter2"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter2"
		"font"					"Default"
		"xpos" "405"
		"ypos" "430"
		"zpos"					"2"
		"wide"					"25"
		"tall"					"8"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}

	"ChargeMeter3"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter3"
		"font"					"Default"
		"xpos" "450"
		"ypos" "430"
		"zpos"					"2"
		"wide"					"25"
		"tall"					"8"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}

	"ChargeMeter4"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter4"
		"font"					"Default"
		"xpos" "495"
		"ypos" "430"
		"zpos"					"2"
		"wide"					"25"
		"tall"					"8"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}

}
