

	"Resource/UI/HudPlayerHealth.res" 
	{
	"HudPlayerHealth" 
	{
	"ControlName" "EditablePanel"
	"fieldName" "HudPlayerHealth"
	"xpos" "0"
	"ypos" "-17"
	"zpos" "2"
	"wide" "f0"
	"tall" "480"
	"visible" "1"
	"enabled" "1"
	"HealthBonusPosAdj" "35"
	"HealthDeathWarning" "0.49"
	"HealthDeathWarningColor" "HUDDeathWarning"
	}
	"PlayerStatusHealthImage" 
	{
	"ControlName" "ImagePanel"
	"fieldName" "PlayerStatusHealthImage"
	"xpos" "294"
	"ypos" "262"
	"zpos" "4"
	"wide" "70"
	"tall" "70"
	"visible" "0"
	"enabled" "1"
	"scaleImage" "1"
	"alpha" "0"
	}
	"PlayerStatusHealthImageBG" 
	{
	"ControlName" "ImagePanel"
	"fieldName" "PlayerStatusHealthImageBG"
	"xpos" "10188"
	"ypos" "10261"
	"zpos" "3"
	"wide" "55"
	"tall" "55"
	"visible" "0"
	"enabled" "1"
	"image" "../hud/health_bg"
	"scaleImage" "1"
	}
	"PlayerStatusHealthBonusImage" 
	{
	"ControlName" "ImagePanel"
	"fieldName" "PlayerStatusHealthBonusImage"
	"xpos" "9999"
	"ypos" "40"
	"zpos" "-1"
	"wide" "22"
	"tall" "22"
	"visible" "0"
	"enabled" "1"
	"image" "../hud/health_over_bg"
	"scaleImage" "1"
	}
	"PlayerStatusHealthValue" 
	{
	"ControlName" "CExLabel"
	"fieldName" "PlayerStatusHealthValue"
	"xpos" "210"
	"ypos" "319"
	"zpos" "5"
	"wide" "300"
	"tall" "100"
	"visible" "1"
	"enabled" "1"
	"labelText" "%Health%"
	"textAlignment" "north"
	"font" "HandelGothicBT30"
	"fgcolor" "255 255 255 255"
	}
	"PlayerStatusHealthValueShadow" 
	{
	"ControlName" "CExLabel"
	"fieldName" "PlayerStatusHealthValueShadow"
	"xpos" "211"
	"ypos" "320"
	"zpos" "5"
	"wide" "300"
	"tall" "100"
	"visible" "1"
	"enabled" "1"
	"labelText" "%Health%"
	"textAlignment" "north"
	"font" "HandelGothicBT30"
	"fgcolor" "34 34 34 255"
	}
	"PlayerStatusBleedImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatusBleedImage"
		"xpos" "9999"
		"ypos" "277"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "0"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../vgui/bleed_drop"
		"fgcolor" "TanDark"
	}
	"PlayerStatusMilkImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatusMilkImage"
		"xpos" "9999"
		"ypos" "277"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "0"
		"enabled" "0"
		"scaleImage" "1"
		"image" "../vgui/bleed_drop"
		"fgcolor" "TanDark"
	}
	"PlayerStatusMarkedForDeathImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatusMarkedForDeathImage"
		"xpos" "99999"
		"ypos" "9999"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "0"
		"enabled" "0"
		"scaleImage" "1"
		"image" "../vgui/marked_for_death"
		"fgcolor" "TanDark"
	}
	"PlayerStatusMarkedForDeathSilentImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatusMarkedForDeathSilentImage"
		"xpos" "9999"
		"ypos" "9999"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "0"
		"enabled" "0"
		"scaleImage" "1"
		"image" "../vgui/marked_for_death"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicUberBulletResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicUberBulletResistImage"
		"xpos" "115"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_bullet_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicUberBlastResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicUberBlastResistImage"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_explosion_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicUberFireResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicUberFireResistImage"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_fire_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicSmallBulletResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicSmallBulletResistImage"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_bullet_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicSmallBlastResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicSmallBlastResistImage"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_explosion_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_MedicSmallFireResistImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_MedicSmallFireResistImage"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_fire_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_WheelOfDoom" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_WheelOfDoom"
		"xpos" "9999"
		"ypos" "15"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../signs/death_wheel_whammy"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_SoldierOffenseBuff" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_SoldierOffenseBuff"
		"xpos" "85"
		"ypos" "0"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_bullet_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_SoldierDefenseBuff" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_SoldierDefenseBuff"
		"xpos" "85"
		"ypos" "0"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_bullet_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_SoldierHealOnHitBuff" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_SoldierHealOnHitBuff"
		"xpos" "85"
		"xpos_minmode" "70"
		"ypos" "0"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "../HUD/defense_buff_bullet_blue"
		"fgcolor" "TanDark"
	}
	"PlayerStatus_Parachute" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "PlayerStatus_Parachute"
		"xpos" "9999"
		"ypos" "262"
		"zpos" "7"
		"wide" "24"
		"tall" "24"
		"visible" "0"
		"enabled" "1"
		"scaleImage" "1"
		"image" ""
		"fgcolor" "TanDark"
	}
	"HealthBG" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "HealthBG"
		"xpos" "240"
		"ypos" "413"
		"zpos" "-10"
		"wide" "130"
		"tall" "50"
		"autoResize" "0"
		"visible" "0"
		"enabled" "1"
		"defaultBgColor_Override" "QHUDBlank"
		"PaintBackgroundType" "0"
		"textinsety" "99"
	}
	"PlayerStatusBleedImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusBleedImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"32"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../vgui/bleed_drop"
			"fgcolor"		"TanDark"
		}
		"PlayerStatusHookBleedImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusHookBleedImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"8"
			"wide"			"32"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../vgui/bleed_drop_grapple"
			"fgcolor"		"TanDark"
		}
		"PlayerStatusMilkImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusMilkImage"
			"xpos"			"117"
			"xpos_minmode"	"102"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"32"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../vgui/bleed_drop"
			"fgcolor"		"TanDark"
		}
		"PlayerStatusMarkedForDeathImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusMarkedForDeathImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"32"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../vgui/marked_for_death"
			"fgcolor"		"TanDark"
		}
		"PlayerStatusMarkedForDeathSilentImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatusMarkedForDeathSilentImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../vgui/marked_for_death"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_MedicUberBulletResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicUberBulletResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_bullet_blue"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_MedicUberBlastResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicUberBlastResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_explosion_blue"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_MedicUberFireResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicUberFireResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_fire_blue"
			"fgcolor"		"TanDark"
		}

		"PlayerStatus_MedicSmallBulletResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicSmallBulletResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_bullet_blue"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_MedicSmallBlastResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicSmallBlastResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_explosion_blue"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_MedicSmallFireResistImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_MedicSmallFireResistImage"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_fire_blue"
			"fgcolor"		"TanDark"
		}
		

		"PlayerStatus_WheelOfDoom"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_WheelOfDoom"
			"xpos"			"130"
			"xpos_minmode"	"145"
			"ypos"			"38"
			"ypos_minmode"	"55"
			"zpos"			"7"
			"wide"			"32"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../signs/death_wheel_whammy"
			"fgcolor"		"TanDark"
		}

		"PlayerStatus_SoldierOffenseBuff"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_SoldierOffenseBuff"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_bullet_blue"
			"fgcolor"		"TanDark"
		}

		"PlayerStatus_SoldierDefenseBuff"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_SoldierDefenseBuff"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_bullet_blue"
			"fgcolor"		"TanDark"
		}

		"PlayerStatus_SoldierHealOnHitBuff"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_SoldierHealOnHitBuff"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../HUD/defense_buff_bullet_blue"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_SpyMarked"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_SpyMarked"
			"xpos"			"115"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"0"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			""
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_Parachute"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_Parachute"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"0"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			""
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneStrength"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneStrength"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_strength_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneHaste"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneHaste"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_haste_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneRegen"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneRegen"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_regen_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneResist"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneResist"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_resist_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneVampire"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneVampire"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_vampire_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneReflect"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneReflect"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_reflect_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RunePrecision"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RunePrecision"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_precision_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneAgility"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneAgility"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_agility_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneKnockout"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneKnockout"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_knockout_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneKing"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneKing"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_king_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RunePlague"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RunePlague"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_plague_hud"
			"fgcolor"		"TanDark"
		}
		"PlayerStatus_RuneSupernova"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"PlayerStatus_RuneSupernova"
			"xpos"			"85"
			"xpos_minmode"	"70"
			"ypos"			"0"
			"zpos"			"7"
			"wide"			"31"
			"tall"			"31"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"	
			"image"			"../Effects/powerup_supernova_hud"
			"fgcolor"		"TanDark"
		}
	}
