"Resource/UI/HudItemEffectMeter.res"
{
	"HudItemEffectMeter"
	{
		"fieldName"									"HudItemEffectMeter"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"f0"
		"tall"										"480"
		"visible"									"1"
		"enabled"									"1"
	}
	"pagermod"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"pagermod"
		"xpos"										"rs1-46"
		"ypos"										"rs1-83"
		"zpos"										"10"
		"wide"										"80"
		"tall"										"31"
		"visible"									"1"
		"enabled"									"1"
		"image"										"replay/thumbnails/pager1"
		"scaleImage"								"1"
	}
	"pagerwhite"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"pagerwhite"
		"xpos"										"rs1-46"
		"ypos"										"rs1-83"
		"zpos"										"-10"
		"wide"										"80"
		"tall"										"31"
		"visible"									"1"
		"enabled"									"1"
		"image"										"replay/thumbnails/pager1white"
		"scaleImage"								"1"
	}
	"ItemEffectMeter"
	{
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ItemEffectMeter"
		"xpos"										"rs1-58+1"
		"ypos"										"rs1-90"
		"zpos"										"0"
		"wide"										"60"
		"tall"										"4"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"bgcolor_override" "blank"
	}
	"bg1"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"bg1"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"-1"
		"wide"										"88"
		"tall"										"3"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"labelText"									""
		"textAlignment"								"east"
		"font"										"hudfontsmall"
		"bgcolor_override" "black"
		"paintBackgroundtype" "0"
		"roundcorner" "2"
		"pin_to_sibling" "ItemEffectMeter"
	}
	"ItemEffectMeterLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ItemEffectMeterLabel"
		"xpos"										"0"
		"ypos"										"15"
		"zpos"										"2"
		"wide"										"60"
		"tall"										"18"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"labelText"									"#TF_Ball"
		"textAlignment"								"west"
		"font"										"HudFontSmallestBold"
		"pin_to_sibling" "ItemEffectMeter"
	}
	"grad"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"grad"
		"xpos"										"rs1-43"
		"ypos"										"rs1-102"
		"zpos"										"5"
		"wide"										"92"
		"tall"										"16"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"scaleImage" "1"
		"image" "replay/thumbnails/gradadd"
		"alpha" "175"
 
	}
		"grad1"
	{
		"ControlName"								"ImagePanel"
		"fieldName"									"grad1"
		"xpos"										"rs1-43"
		"ypos"										"rs1-98"
		"zpos"										"5"
		"wide"										"92"
		"tall"										"6"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"scaleImage" "1"
		"image" "replay/thumbnails/gradmulti"
		"alpha" "255"
 
	}
	"bg"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"bg"
		"xpos"										"rs1-43"
		"ypos"										"rs1-98"
		"zpos"										"-1"
		"wide"										"92"
		"tall"										"20"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"labelText"									""
		"textAlignment"								"east"
		"font"										"hudfontsmall"
		"bgcolor_override" "0 0 255 255"
		"paintBackgroundtype" "0"
		"roundcorner" "2"
	}
		"bg2"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"bg2"
		"xpos"										"rs1-42"
		"ypos"										"rs1-97"
		"zpos"										"-2"
		"wide"										"94"
		"tall"										"22"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"labelText"									""
		"textAlignment"								"east"
		"font"										"hudfontsmall"
		"bgcolor_override" "255 255 255 255"
		"paintBackgroundtype" "0"
		"roundcorner" "2"
	}
}