"Resource/UI/HudObjectiveKothTimePanel.res"
{
	"BlueTimerBG"
	{
		"ControlName"								"Panel"
		"fieldName"									"BlueTimerBG"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"paintbackground"							"1"
		"bgcolor_override"							"HUDBlueTeamSolid"
		"alpha"										"200"
	}
	"BlueTimer"
	{
		"ControlName"								"CTFHudTimeStatus"
		"fieldName"									"BlueTimer"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"2"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"TimePanelValue"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"TimePanelValue"
			"xpos"									"155"
			"ypos"									"202"
			"zpos"									"3"
			"wide"									"f0"
			"tall"									"f0"
			"visible"								"1"
			"enabled"								"1"
			"proportionaltoparent"					"1"
			"textAlignment"							"west"
			"labelText"								"0:00"
			"font"									"ArialBold"
			"fgcolor"								"blue"
		}
	}
	"RedTimerBG"
	{
		"ControlName"								"Panel"
		"fieldName"									"RedTimerBG"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"paintbackground"							"1"
		"bgcolor_override"							"HUDRedTeamSolid"
		"alpha"										"200"
	}
	"RedTimer"
	{
		"ControlName"								"CTFHudTimeStatus"
		"fieldName"									"RedTimer"
		"xpos"									"0"
		"ypos"									"0"
		"zpos"										"2"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"

		"TimePanelValue"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"TimePanelValue"
			"xpos"									"155"
			"ypos"									"216"
			"zpos"									"3"
			"wide"									"f0"
			"tall"									"f0"
			"visible"								"1"
			"enabled"								"1"
			"proportionaltoparent"					"1"
			"textAlignment"							"west"
			"labelText"								"0:00"
			"font"									"ArialBold"
			"fgcolor"								"red"
		}
	}
	"ActiveTimerBG"
	{
		"ControlName"								"Panel"
		"fieldName"									"ActiveTimerBG"
		"xpos"										"0"
		"ypos"										"15"
		"zpos"										"1"
		"wide"										"0"
		"tall"										"2"
		"visible"									"0"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"paintbackground"							"1"
		"bgcolor_override"							"White"
	}
}