"Resource/UI/TargetID.res"
{
	"TargetNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TargetNameLabel"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"640"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"0"
		"proportionaltoparent"						"1"
		"labelText"									"%targetname%"
		"textAlignment"								"west"
		"font"										"MatchTime"
		"disabledfgcolor2_override"					"255 255 255 255"
	}
	"TargetDataLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TargetDataLabel"
		"xpos"										"0"
		"ypos"										"17"
		"zpos"										"1"
		"wide"										"280"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"0"
		"proportionaltoparent"						"1"
		"labelText"									"%targetdata%"
		"textAlignment"								"west"
		"font"										"ArialBlacksmall"
		"disabledfgcolor2_override"					"255 255 255 255"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"SpectatorGUIHealth"
		"xpos"										"3"
		"ypos"										"-2"
		"wide"										"35"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"HealthBonusPosAdj"							"10"
		"HealthDeathWarning"						"0.49"
		"TFFont"									"MatchTime"
		"HealthDeathWarningColor"					"HUDDeathWarning"
		"TextColor"									"HudOffWhite"

	"PlayerStatusHealthValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValue"
		"xpos"			"-1"
		"xpos_minmode"	"7"
		"ypos"			"5"
		"ypos_minmode"	"7"
		"zpos"			"5"
		"wide"			"35"
		"wide_minmode"	"14"
		"tall"			"15"
		"tall_minmode"	"14"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%Health%"
		"textAlignment"	"center"	
		"font"			"MatchTime"
		"fgcolor"		"255 255 255 255"
	}
	}
}