"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"49999"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"90"
		"tall"			"45"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ammo_red_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"			
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"Jost60"
		"font_minmode"			"Jost38"
		"fgcolor"		"TanLight"
		"xpos"			"0"
		"ypos"			"25"
		"xpos_minmode"	"5"
		"ypos_minmode"	"33"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"Jost60" 
		"font_minmode"			"Jost38"
		"fgcolor"		"Black"
		"xpos"			"1"
		"ypos"			"26"
		"xpos_minmode"	"6"
		"ypos_minmode"	"34"
		"zpos"			"5"
		"wide"			"81"
		"tall"			"51"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"          "Jost26"
		"font_minmode"  "Jost22"
		"fgcolor"		"TanLight"
		"xpos"			"73"
		"ypos"			"35"
		"xpos_minmode"  "70" 
		"ypos_minmode"  "40"  
		"zpos"			"7"
		"wide"			"51"
		"tall"			"26"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"          "Jost26"
		"font_minmode"  "Jost22"
		"fgcolor"		"Black"
		"xpos"			"-1"
		"xpos_minmode"  "-1"
		"ypos"			"1"
		"wide"			"50"
		"tall"			"26"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"		
		"labelText"		"%AmmoInReserve%"
		
		"pin_to_sibling"		"AmmoInReserve"
		"pin_corner_to_sibling"	"2"
		"pin_to_sibling_corner"	"2"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"Jost60"
		"font_minmode"			"Jost38"
		"fgcolor"		"TanLight"
		"xpos"			"14"
		"ypos"			"25"
		"xpos_minmode"	"14"
		"ypos_minmode"	"33"
		"zpos"			"5"
		"wide"			"80"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"Jost60"
		"font_minmode"			"Jost38"
		"fgcolor"		"Black"
		"xpos"			"15"
		"ypos"			"26"
		"xpos_minmode"	"15"
		"ypos_minmode"	"34"
		"zpos"			"5"
		"wide"			"81"
		"tall"			"51"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"		
		"labelText"		"%Ammo%"
	}									
}
