"Resource/UI/HudMedicCharge.res"
{	
	"Background"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"65"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/medic_charge_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/medic_charge_red_bg"
		"teambg_3"		"../hud/medic_charge_blue_bg"				
	}
	
	"ChargeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ChargeLabel"
		"xpos"			"190"
		"ypos"			"38"
		"zpos"			"2"
		"wide"			"130"
		"tall"			"56" 
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_UberchargeMinHUD"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Jost60Shadow"
		"fgcolor"		"white"
		
		"font_minmode"	"Jost38Shadow"
		"xpos_minmode"	"155"
		"ypos_minmode"	"22"
		"wide_minmode"	"91"
		"tall_minmode"	"37" 
	}	

	"IndividualChargesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"IndividualChargesLabel"
		"xpos"			"170"
		"ypos"			"38"
		"zpos"			"2"
		"wide"			"130"
		"tall"			"56"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_IndividualUberchargesMinHUD"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"Jost60Shadow"
		
		"font_minmode"	"Jost38Shadow"
		"xpos_minmode"	"145"
		"ypos_minmode"	"22"
		"wide_minmode"	"91"
		"tall_minmode"	"37"
	}
	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"55"
		"ypos"			"69"
		"zpos"			"2"
		"wide"			"88"
		"tall"			"4"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"0 0 0 0"
		"fgcolor_override"	"255 255 255 255"
		
		"xpos_minmode"			"50"
		"ypos_minmode"			"50"
		"wide_minmode"			"100"
	}	
	
	"ChargeMeterBGshade"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ChargeMeterBGshade"
		"xpos"			"54"
		"ypos"			"68"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"6"	
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"22 22 22 222"
		"PaintBackgroundType""0"
		
		"xpos_minmode"			"49"
		"ypos_minmode"			"49"
		"wide_minmode"			"102"
	}

	"ChargeMeter1"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter1"
		"font"			"Default"
		"xpos"			"55"
		"ypos"			"69"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"4"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"0 0 0 0"
		"fgcolor_override"	"255 255 255 255"
		
		"xpos_minmode"			"50"
		"ypos_minmode"			"50"
		"wide_minmode"			"24"
	}

	"ChargeMeter2"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter2"
		"font"			"Default"
		"xpos"			"77"
		"ypos"			"69"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"4"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"0 0 0 0"
		"fgcolor_override"	"255 255 255 255"
		
		"xpos_minmode"			"76"
		"ypos_minmode"			"50"
		"wide_minmode"			"23"
	}

	"ChargeMeter3"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter3"
		"font"			"Default"
		"xpos"			"100"
		"ypos"			"69"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"4"			
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"0 0 0 0"
		"fgcolor_override"	"255 255 255 255"
		
		"xpos_minmode"			"101"
		"ypos_minmode"			"50"
		"wide_minmode"			"23"
	}

	"ChargeMeter4"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter4"
		"font"			"Default"
		"xpos"			"122"
		"ypos"			"69"
		"zpos"			"2"
		"wide"			"21"
		"tall"			"4"			
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"bgcolor_override"	"0 0 0 0"
		"fgcolor_override"	"255 255 255 255"
		
		"xpos_minmode"			"126"
		"ypos_minmode"			"50"
		"wide_minmode"			"24"
	}
	
	"HealthClusterIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthClusterIcon"
		"xpos"			"2"
		"ypos"			"17"
		"wide"			"36"
		"tall"			"36"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/ico_health_cluster"
		"scaleImage"	"1"	
	}	
	
	"ResistIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ResistIcon"
		"xpos"			"0"
		"ypos"			"-25"
		"wide"			"22"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../HUD/defense_buff_bullet_blue"
		"scaleImage"	"1"	
	}
}
