"Resource/UI/DisguiseStatusPanel.res"
{
	"ItemModelPanel"
	{
		"ControlName"								"CEmbeddedItemModelPanel"
		"fieldName"									"ItemModelPanel"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"100"
		"tall"										"100"
		"visible"									"1"
		"enabled"									"1"

		"useparentbg"								"1"
		"fov"										"54"
		"start_framed"								"1"
		"disable_manipulation"						"1"

		"Model"
		{
			"angles_x"								"10"
			"angles_y"								"130"
			"angles_z"								"0"
		}
	}
	"DisguiseStatusBG"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"DisguiseStatusBG"
		"xpos"										"15"
		"ypos"										"r26"
		"zpos"										"-1"
		"wide"										"28"
		"tall"										"14"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"

		"image"										"../hud/color_panel_brown"
		"scaleImage"								"1"
		"teambg_1"									"../hud/color_panel_brown"
		"teambg_2"									"replay\thumbnails\c_red"
		"teambg_3"									"replay\thumbnails\c_blue"
		"alpha" "175"

		"src_corner_height"							"23"
		"src_corner_width"							"23"
		"draw_corner_width"							"0"
		"draw_corner_height"						"0"
	}
	"DisguiseNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"DisguiseNameLabel"
		"xpos"										"-30"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"0"
		"tall"										"12"
		"visible"									"0"
		"enabled"									"1"
		"labelText"									"%disguisename%"
		"font"										"typosterReg10"
		"textAlignment"								"West"
		"fgcolor"									"White"

		"pin_to_sibling"							"DisguiseStatusBG"
		"pin_corner_to_sibling"						"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"						"PIN_CENTER_LEFT"
	}
	"WeaponNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"WeaponNameLabel"
		"xpos"										"2"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"123"
		"tall"										"14"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"%weaponname%"
		"font"										"typosterReg10"
		"textAlignment"								"West"
		"fgcolor"									"White"

		"pin_to_sibling"							"DisguiseStatusBG"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_TOPRIGHT"
	}
		"WeaponNameLabelShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"WeaponNameLabelShadow"
		"xpos"										"3"
		"ypos"										"-1"
		"zpos"										"1"
		"wide"										"123"
		"tall"										"13"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"%weaponname%"
		"font"										"typosterReg10"
		"textAlignment"								"West"
		"fgcolor"									"black"

		"pin_to_sibling"							"DisguiseStatusBG"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_TOPRIGHT"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"SpectatorGUIHealth"
		"xpos"										"4"
		"ypos"										"6"
		"wide"										"36"
		"wide_disabled"								"35"
		"tall"										"26"
		"tall_disabled"								"38"
		"visible"									"1"
		"enabled"									"1"
		"HealthBonusPosAdj"							"10"
		"HealthDeathWarning"						"0.49"
		"TFFont"									"HudFontSmall"
		"HealthDeathWarningColor"					"HUDDeathWarning"
		"TextColor"									"HudOffWhite"

		"pin_to_sibling"							"DisguiseStatusBG"
	}
}