"Resource/UI/FreezePanelKillerHealth.res"
{
	"PlayerStatusHealthImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"PlayerStatusHealthImage"
		"xpos"		"5"
		"ypos"		"-8"
		"zpos"		"4"
		"wide"		"20"
		"tall"		"20"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"0"	
	}		
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"PlayerStatusHealthImageBG"
		"xpos"		"5"
		"ypos"		"5"
		"zpos"		"3"
		"wide"		"0"
		"tall"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"		"../hud/health_bg"
		"scaleImage"	"0"	
	}	
	"BuildingStatusHealthImageBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"PlayerStatusHealthImageBG"
		"xpos"		"1"
		"ypos"		"2"
		"zpos"		"3"
		"wide"		"0"
		"tall"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"		"../hud/health_equip_bg"
		"scaleImage"	"0"	
	}	
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"PlayerStatusHealthBonusImage"
		"xpos"		"5"
		"ypos"		"5"
		"zpos"		"3"
		"wide"		"0"
		"tall"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"		"../hud/health_over_bg"
		"scaleImage"	"0"	
	}
	"PlayerStatusHealthValue"
	{
		"ControlName"	"Label"
		"fieldName"	"PlayerStatusHealthValue"
		"xpos"		"-7"
		"ypos"		"8"
		"zpos"		"5"
		"wide"		"50"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"font"		"surface24shadow"
		"labelText"	"%Health%"
	}								
}
