"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"		"28"
		"ypos"		"7"
		"zpos"		"1"
		"wide"		"0"
		"tall"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"		"../hud/ammo_blue_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_3"		"../hud/ammo_blue_bg"
	}
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"		"800"
		"ypos"		"17"
		"zpos"		"0"
		"wide"		"0"
		"tall"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"		"../hud/ammo_red_bg"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_3"		"../hud/ammo_blue_bg"
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"		"surfaceHPAmmo72"
		"fgcolor"		"255 255 255 255"
		"xpos"		"-90"
		"ypos"		"3"
		"zpos"		"5"
		"wide"		"200"
		"tall"		"65"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		
		
		"font_minmode"		"surfaceHPAmmo42"
		"xpos_minmode"		"-95"
		"ypos_minmode"		"0"
	}
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"		"surfaceHPAmmo72"
		"fgcolor"		"0 0 0 255"
		"xpos"		"-89"
		"ypos"		"4"
		"zpos"		"5"
		"wide"		"200"
		"tall"		"65"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"	
		"labelText"		"%Ammo%"
		
		"font_minmode"		"surfaceHPAmmo42"
		"xpos_minmode"		"-94"
		"ypos_minmode"		"1"
		
	}
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"		"surfaceHPAmmo28"
		"fgcolor"		"255 255 255 255"
		"xpos"		"114"
		"ypos"		"23"
		"zpos"		"7"
		"wide"		"80"
		"tall"		"27"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
		
		"font_minmode"		"surface24shadow"
		"xpos_minmode"		"114"
		"ypos_minmode"		"20"
		
	}
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveshadow"
		"font"		"surfaceHPAmmo28"
		"fgcolor"		"0 0 0 255"
		"xpos"		"115"
		"ypos"		"24"
		"zpos"		"7"
		"wide"		"80"
		"tall"		"27"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
		
		"font_minmode"		"null"
		"visible_minmode"	"0"
		"enabled_minmode"	"0"
		"fgcolor_minmode"   "0 0 0 0"
		"alpha_minmode"		"0"
		
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmonoClip"
		"font"		"surfaceHPAmmo72"
		"fgcolor"		"Ammo in Clip"
		"xpos"		"35"
		"ypos"		"3"
		"zpos"		"5"
		"wide"		"125"
		"tall"		"65"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
		"font_minmode"		"surfaceHPAmmo42"
		"ypos_minmode"		"-1"
		"xpos_minmode"		"40"
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmonoClipshadow"
		"font"		"surfaceHPAmmo72"
		"fgcolor"		"0 0 0 255"
		"xpos"		"36"
		"ypos"		"4"
		"zpos"		"5"
		"wide"		"125"
		"tall"		"65"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
		"font_minmode"		"surfaceHPAmmo42"
		"ypos_minmode"		"0"
		"xpos_minmode"		"41"
	}									
}
