#base "../../resource/default/CharInfoPanel.res"

"Resource/UI/CharInfoPanel.res"
{
	"BackButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"BackButton"
		"xpos"										"r580"
		"ypos"										"r35"
		"zpos"										"2"
		"wide"										"100"
		"tall"										"25"
		"autoResize"								"0"
		"pinCorner"									"3"
		"visible"									"1"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Back (&Q)"
		"font"										"SurfaceBold15"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"
		"default"									"0"
		"Command"									"back"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"
		"border_default"							"noborder"
		"bgcolor_override"				"20 20 20 255"
		"defaultBgColor_override"		"20 20 20 255"
		"armedBgColor_override"			"babyblue"
		"armedFgColor_override" 				"20 20 20 255"
		"depressedFgColor_override" 			"20 20 20 255"
	}
	
	"CloseButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"CloseButton"
		"xpos"										"r110"
		"ypos"										"r35"
		"zpos"										"2"
		"wide"										"100"
		"tall"										"25"
		"autoResize"								"0"
		"pinCorner"									"3"
		"visible"									"1"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Close (&E)"
		"font"										"SurfaceBold15"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"
		"default"									"0"
		"Command"									"close"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"
		"border_default"							"noborder"
		"bgcolor_override"				"20 20 20 255"
		"defaultBgColor_override"		"20 20 20 255"
		"armedBgColor_override"			"babyblue"
		"armedFgColor_override" 				"20 20 20 255"
		"depressedFgColor_override" 			"20 20 20 255"
	}
	
	"ReloadSchemeButton"
	{
		"xpos"										"r20"
		"ypos"										"30"
	}
}