#base "../../cfg/m0re_speedometer.txt"
#base "../../cfg/m0re_spy_disguise.txt"
#base "../../scripts/crosshairs/hudcrosshairs.res"
#base "customizations/uber/ubercounter.res"
#base "hudplayerclass_base.res"