"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}

	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"		
	}
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"HudFontHUGE"
		"font_minmode"			"HudFontGiantBold"
		"fgcolor"		"TanLight"
		"xpos"			"0"
		"ypos"			"22"
		"zpos"			"5"
		"wide"			"100"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"HudFontHUGE"
		"font_minmode"			"HudFontGiantBold"
		"fgcolor"		"SuperBlack"
		"xpos"			"3"
		"ypos"			"25"
		"xpos_minmode"			"2"
		"ypos_minmode"			"24"
		"zpos"			"4"
		"wide"			"100"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
	}						
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"HudFontBiggerBold"
		"font_minmode"	"HudFontMediumBold"
		"fgcolor"		"TanLight"
		"xpos"			"100"
		"xpos_minmode"			"93"
		"ypos"			"44"
		"ypos_minmode"			"41"
		"zpos"			"7"
		"wide"			"84"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"HudFontBiggerBold"
		"font_minmode"	"HudFontMediumBold"
		"fgcolor"		"SuperBlack"
		"xpos"			"103"
		"ypos"			"46"
		"xpos_minmode"			"94"
		"ypos_minmode"			"43"
		"zpos"			"7"
		"wide"			"84"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%AmmoInReserve%"
	}									
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"HudFontHUGE"
		"font_minmode"			"HudFontGiantBold"
		"fgcolor"		"TanLight"
		"xpos"			"20"
		"ypos"			"22"
		"zpos"			"5"
		"wide"			"170"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%Ammo%"
		
	}	
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"HudFontHUGE"
		"font_minmode"			"HudFontGiantBold"
		"fgcolor"		"SuperBlack"
		"xpos"			"23"
		"ypos"			"25"
		"xpos_minmode"			"22"
		"ypos_minmode"			"24"
		"zpos"			"5"
		"wide"			"170"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"		
		"labelText"		"%Ammo%"
		
	}									
}
