"Resource/UI/HudDemomanPipes.res"
{
	"background"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"background"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"			
	}
	
	"ChargeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChargeLabel"
		"xpos"										"c-19"
		"ypos"										"365"
		"zpos"										"2"
		"wide"										"80"
		"tall"										"50"
		"autoResize"								"1"
		"pinCorner"									"2"
		"visible"									"1"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Shield:"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"
		"font"										"M0refont14"
		"fgcolor_override"							"255 255 255 255"
	}

	"ChargeMeter"
	{	
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ChargeMeter"
		"xpos"										"c61"	
		"ypos"										"383"	
		"zpos"										"2"
		"wide"										"40"
		"tall"										"13"		
		"autoResize"								"0"
		"pinCorner"									"0"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"Left"
		"dulltext"									"0"
		"brighttext"								"0"
	}	

	"ChargeMeterBG"
	{	
		  "ControlName"     "EditablePanel"
		  "fieldName"    "ChargeMeterBG"
		  "xpos"		"c-20"		
	      "ypos"		"380"	 
		  "wide"         "125"
		  "tall"         "19"  		 
		  "autoResize"   "0"
		  "pinCorner"    "0"
		  "visible"      "1"
		  "enabled"      "1"
		  "bgcolor_override"   "0 0 0 255"
	}				
		
	"PipesPresentPanel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PipesPresentPanel"
		"xpos"										"0"		
		"ypos"										"86"	
		"zpos"										"3"
		"wide"										"f0"
		"tall"										"480"
		"visible"									"1"
		
		"PipeIcon"
		{
			"ControlName"							"CTFImagePanel"
			"fieldName"								"PipeIcon"
			"wide"									"0"
			"tall"									"0"
			"visible"								"0"
			"enabled"								"0"
		}	
		
		"StickiesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"StickiesLabel"
			"xpos"									"c-15"	
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"150"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"Stickies:"
			"textAlignment"							"west"
			"dulltext"								"0"
			"brighttext"							"0"
	    	"font"									"M0refont14"	
			"fgcolor"   							"255 255 255 255"
		}			
		
		"NumPipesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"NumPipesLabel"
			"xpos"									"c68"	
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"30"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"%activepipes%"
			"textAlignment"							"center"
			"dulltext"								"0"
			"brighttext"							"0"
			"font"									"M0refont14"	
			"fgcolor"   							"255 255 255 255"
		}
			
		"Outof8Label"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Outof8Label"
			"xpos"									"c66"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"40"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"/8"
			"textAlignment"							"east"
			"dulltext"								"0"
			"brighttext"							"0"
			"font"									"M0refont14"
			"fgcolor"   							"255 255 255 255"
		}		
	}
	
	"NoPipesPresentPanel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"NoPipesPresentPanel"
		"xpos"										"0"
		"ypos"										"86"	
		"zpos"										"3"
		"wide"										"f0"
		"tall"										"480"
		"visible"									"1"
		
		"StickiesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"StickiesLabel"
			"xpos"									"c-15"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"150"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"Stickies:"
			"textAlignment"							"west"
			"dulltext"								"0"
			"brighttext"							"0"
			"font"										"M0refont14"
			"fgcolor"   							"255 255 255 255"
		}			
		
		"NumPipesLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"NumPipesLabel"
			"xpos"									"c68"	
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"30"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"%activepipes%"
			"textAlignment"							"center"
			"dulltext"								"0"
			"brighttext"							"0"
			"font"									"M0refont14"	
			"fgcolor"   							"255 255 255 255"
		}
			
		"Outof8Label"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Outof8Label"
			"xpos"									"c66"
			"ypos"									"c54"
			"zpos"									"2"
			"wide"									"40"
			"tall"									"20"
			"autoResize"							"1"
			"pinCorner"								"2"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labelText"								"/8"
			"textAlignment"							"east"
			"dulltext"								"0"
			"brighttext"							"0"
			"font"									"M0refont14"
			"fgcolor"   							"255 255 255 255"
		}
}
