"Resource/UI/HudDemomanCharge.res"
{	
	"ChargeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChargeLabel"
		"xpos"										"c198"	
		"ypos"										"422"
		"zpos"										"2"
		"wide"										"80"
		"tall"										"50"
		"autoResize"								"1"
		"pinCorner"									"2"
		"visible"									"1"
		"enabled"									"1"
		"tabPosition"								"0"
		"labelText"									"Charge:"
		"textAlignment"								"center"
		"dulltext"									"0"
		"brighttext"								"0"
		"font"										"M0refont14"
		"fgcolor_override"							"255 255 255 255"
	}

	"ChargeMeter"
	{	
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ChargeMeter"
		"font"										"Default"
		"xpos"										"c278"
		"ypos"										"440"		
		"zpos"										"2"
		"wide"										"40"
		"tall"										"13"	
		"autoResize"								"0"
		"pinCorner"									"0"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"Left"
		"dulltext"									"0"
		"brighttext"								"0"
		"fgcolor_override"							"255 255 255 255"
	}				
   
   "ChargeBG"
    {
		  "ControlName"     "EditablePanel"
		  "fieldName"    "ChargeMeterBG"
		  "xpos"		"c198"		  
		  "ypos"		"437"
		  "wide"         "124"
		  "tall"         "19"  	  
		  "autoResize"   "0"
		  "pinCorner"    "0"
		  "visible"      "1"
		  "enabled"      "1"
		  "bgcolor_override"   "0 0 0 255"
	}				
}
